"""coder — Unity C# scaffolding (template-driven).

Templates live at `skills/game-dev-agent/templates/cs/*.cs.tmpl`.
Adding a new template = adding a new file.  Each template encodes
zero or more "lessons" (bug patterns we hit and don't want to hit
again) as comments at the top.

Variables substituted:
    {{CLASS_NAME}}    — C# class name
    {{NAMESPACE}}     — C# namespace (default MelonS.GameProto)
    {{DESCRIPTION}}   — XML-doc summary line

Future [OPQ-002]: when ANTHROPIC_API_KEY is set, coder falls back
to Claude API for arbitrary specs ("WASD movement with grid-snap")
that don't match an existing template.  Claude proposes a new
template; operator approves; saved to disk; becomes a permanent
codegen primitive.  This is the "끊임없이 최적화" feedback loop:
new game → new template → all future games benefit.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional


TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "cs"


def list_templates(templates_dir: Optional[Path] = None) -> list[str]:
    d = templates_dir or TEMPLATES_DIR
    return sorted(p.stem.removesuffix(".cs") if p.stem.endswith(".cs") else p.stem
                  for p in d.glob("*.cs.tmpl"))


def _load_template(slug: str, templates_dir: Optional[Path] = None) -> str:
    d = templates_dir or TEMPLATES_DIR
    path = d / f"{slug}.cs.tmpl"
    if not path.exists():
        available = list_templates(d)
        raise ValueError(
            f"Unknown template '{slug}'.  Available: {available}.  "
            f"Add a new template by dropping a file in {d}."
        )
    return path.read_text(encoding="utf-8")


def scaffold(
    class_name: str,
    template: str,
    description: str = "Generated by game-dev-agent",
    namespace: str = "MelonS.GameProto",
    templates_dir: Optional[Path] = None,
) -> str:
    """Render a C# template with the given class name + description."""
    body = _load_template(template, templates_dir)
    return (body
            .replace("{{CLASS_NAME}}", class_name)
            .replace("{{NAMESPACE}}", namespace)
            .replace("{{DESCRIPTION}}", description))


def write_script(target_dir: Path, class_name: str, template: str,
                 description: str = "", namespace: str = "MelonS.GameProto"):
    content = scaffold(class_name, template, description, namespace)
    target_dir.mkdir(parents=True, exist_ok=True)
    out = target_dir / f"{class_name}.cs"
    out.write_text(content, encoding="utf-8")
    print(f"[coder] wrote {out}")
    return out


# Backward-compat alias for older code that imports CSHARP_TEMPLATES.
# Returns a dict {slug: ""} so anything that .keys() the dict still works.
CSHARP_TEMPLATES = {slug: "" for slug in list_templates()}


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: coder.py <ClassName> <template-slug> [description]")
        print(f"Templates: {list_templates()}")
        sys.exit(1)
    class_name = sys.argv[1]
    template = sys.argv[2]
    desc = sys.argv[3] if len(sys.argv) > 3 else "scaffolded"
    print(scaffold(class_name, template, desc))
