"""coder — Unity C# scaffolding.

Day 1: returns templates for known script types.  Future [OPQ-002]:
Claude API wrapper for arbitrary specs.
"""
from __future__ import annotations

from pathlib import Path


CSHARP_TEMPLATES = {
    "minimal-monobehaviour": '''using UnityEngine;

namespace MelonS.GameProto
{{
    /// <summary>{description}</summary>
    public class {class_name} : MonoBehaviour
    {{
        private void Start() {{ }}
        private void Update() {{ }}
    }}
}}
''',

    "ui-button-handler": '''using UnityEngine;
using UnityEngine.UI;

namespace MelonS.GameProto
{{
    /// <summary>{description}</summary>
    public class {class_name} : MonoBehaviour
    {{
        [SerializeField] private Button button;

        private void Awake()
        {{
            if (button != null)
            {{
                button.onClick.RemoveListener(OnClick);
                button.onClick.AddListener(OnClick);
            }}
        }}

        public void OnClick() {{ }}
    }}
}}
''',

    "singleton-manager": '''using UnityEngine;

namespace MelonS.GameProto
{{
    /// <summary>{description}</summary>
    public class {class_name} : MonoBehaviour
    {{
        public static {class_name} Instance {{ get; private set; }}

        private void Awake()
        {{
            if (Instance != null && Instance != this) {{ Destroy(gameObject); return; }}
            Instance = this;
        }}
    }}
}}
''',
}


def scaffold(class_name: str, template: str, description: str = "Generated by game-dev-agent") -> str:
    if template not in CSHARP_TEMPLATES:
        raise ValueError(f"Unknown template '{template}'.  Available: {list(CSHARP_TEMPLATES.keys())}")
    return CSHARP_TEMPLATES[template].format(class_name=class_name, description=description)


def write_script(target_dir: Path, class_name: str, template: str, description: str = ""):
    content = scaffold(class_name, template, description)
    target_dir.mkdir(parents=True, exist_ok=True)
    out = target_dir / f"{class_name}.cs"
    out.write_text(content, encoding="utf-8")
    print(f"[coder] wrote {out}")
    return out


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: coder.py <ClassName> <template> [description]")
        print(f"Templates: {list(CSHARP_TEMPLATES.keys())}")
        sys.exit(1)
    class_name = sys.argv[1]
    template = sys.argv[2]
    desc = sys.argv[3] if len(sys.argv) > 3 else "scaffolded"
    print(scaffold(class_name, template, desc))
