using UnityEngine;

namespace MelonS.GameProto
{
    /// <summary>
    /// Day 6 audio bank.  Holds AudioClip references.  Optional —
    /// scripts gracefully no-op if clips are not assigned.
    ///
    /// To populate: drop .wav/.mp3 files into Assets/Audio/ then
    /// wire them in the AudioBank inspector slots.  Generated by
    /// game-dev-agent's audio_gen module (Suno BGM + procedural
    /// SFX) in a future iteration.
    /// </summary>
    public class AudioBank : MonoBehaviour
    {
        public static AudioBank Instance { get; private set; }

        public AudioClip bgm;
        public AudioClip sfxChop;
        public AudioClip sfxSelect;
        public AudioClip sfxHit;       // Day 80 — arrow/melee impact
        public AudioClip sfxHarvest;   // Day 80 — crop harvest
        public AudioClip sfxWolfHowl;  // Day 80 — wolf appear

        [SerializeField] private AudioSource bgmSource;
        [SerializeField] private AudioSource sfxSource;
        private float lastHitTime = -10f;
        private float lastHarvestTime = -10f;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
            if (bgmSource == null) bgmSource = gameObject.AddComponent<AudioSource>();
            if (sfxSource == null) sfxSource = gameObject.AddComponent<AudioSource>();
            bgmSource.loop = true;
            bgmSource.volume = 0.45f;
            sfxSource.volume = 0.7f;
        }

        private void Start()
        {
            if (bgm != null)
            {
                bgmSource.clip = bgm;
                bgmSource.loop = true;
                bgmSource.volume = 0.25f;
                bgmSource.Play();
            }
        }

        public void PlayChop()
        {
            if (sfxChop != null && sfxSource != null) sfxSource.PlayOneShot(sfxChop);
        }

        public void PlaySelect()
        {
            if (sfxSelect != null && sfxSource != null) sfxSource.PlayOneShot(sfxSelect);
        }

        // Day 80: 0.25s throttle so multiple simultaneous hits don't buzz.
        public void PlayHit()
        {
            if (sfxHit == null || sfxSource == null) return;
            if (Time.time - lastHitTime < 0.25f) return;
            lastHitTime = Time.time;
            sfxSource.PlayOneShot(sfxHit, 0.7f);
        }

        public void PlayHarvest()
        {
            if (sfxHarvest == null || sfxSource == null) return;
            if (Time.time - lastHarvestTime < 0.15f) return;
            lastHarvestTime = Time.time;
            sfxSource.PlayOneShot(sfxHarvest, 0.9f);
        }

        public void PlayWolfHowl()
        {
            if (sfxWolfHowl != null && sfxSource != null)
                sfxSource.PlayOneShot(sfxWolfHowl, 0.6f);
        }
    }
}
