using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Events;
using UnityEngine.Events;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.Tilemaps;
using MelonS.GameProto;

namespace MelonS.GameProto.EditorTools
{
    /// <summary>
    /// One-shot scene generator — creates MainMenu.unity + Game.unity
    /// programmatically and registers them in EditorBuildSettings.
    ///
    /// Invoked from CLI:
    ///   Unity.exe -batchmode -quit -projectPath ... -executeMethod
    ///   MelonS.GameProto.EditorTools.SceneSetup.GenerateAll
    /// </summary>
    public static class SceneSetup
    {
        private const string ScenesDir = "Assets/Scenes";
        private const string MainMenuPath = "Assets/Scenes/MainMenu.unity";
        private const string GamePath = "Assets/Scenes/Game.unity";
        private const string PawnPrefabPath = "Assets/Prefabs/Pawn.prefab";
        private const string TreePrefabPath = "Assets/Prefabs/Tree.prefab";

        [MenuItem("MelonS/Generate All Scenes")]
        public static void GenerateAll()
        {
            Debug.Log("[SceneSetup] Starting generation...");
            Directory.CreateDirectory(ScenesDir);
            Directory.CreateDirectory("Assets/Prefabs");

            // CRITICAL: force-import all PNG sprites BEFORE anything tries
            // to load them via AssetDatabase.LoadAssetAtPath<Sprite>().
            // Without this, missing .meta files cause null sprite references.
            ForceImportAllSprites();

            GeneratePawnPrefab();
            GenerateMainMenu();
            GenerateGame();
            RegisterBuildScenes();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[SceneSetup] Done.");
        }

        private static void ForceImportAllSprites()
        {
            string[] paths = new[]
            {
                "Assets/Sprites/pawn_colonist.png",
                "Assets/Sprites/tile_grass.png",
                "Assets/Sprites/tree.png",
                "Assets/Sprites/wall_wood.png",
                "Assets/Sprites/floor_wood.png",
                "Assets/Sprites/door_wood.png",
                "Assets/Sprites/deer.png",
                "Assets/Sprites/stove.png",
            };
            foreach (var p in paths)
            {
                if (!File.Exists(p)) { Debug.LogWarning($"[SceneSetup] missing: {p}"); continue; }
                // Force re-import to ensure .meta exists + Sprite type
                AssetDatabase.ImportAsset(p, ImportAssetOptions.ForceUpdate);
                TextureImporter ti = AssetImporter.GetAtPath(p) as TextureImporter;
                if (ti == null) { Debug.LogWarning($"[SceneSetup] no TextureImporter for {p}"); continue; }
                ti.textureType = TextureImporterType.Sprite;
                ti.spriteImportMode = SpriteImportMode.Single;
                ti.spritePixelsPerUnit = 16;
                ti.filterMode = FilterMode.Point;
                ti.SaveAndReimport();
                Debug.Log($"[SceneSetup] forced sprite import: {p}");
            }
            AssetDatabase.Refresh();
            AssetDatabase.SaveAssets();
        }

        private static void GeneratePawnPrefab()
        {
            // Load the pawn sprite generated by asset_gen
            Sprite pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                "Assets/Sprites/pawn_colonist.png");
            if (pawnSprite == null)
            {
                // Force re-import as Sprite (TextureImporter default may be Default)
                string assetPath = "Assets/Sprites/pawn_colonist.png";
                TextureImporter ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 16;
                    ti.SaveAndReimport();
                    pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                }
            }

            GameObject pawnGo = new GameObject("Pawn");
            // Day 37 영구 fix: pawn 16x16 sprite는 deer 20x20보다 작아 ortho 8
            //  카메라에서 잘 안 보였음.  prefab transform에 2x scale 박음.
            pawnGo.transform.localScale = new Vector3(2f, 2f, 1f);
            SpriteRenderer sr = pawnGo.AddComponent<SpriteRenderer>();
            sr.sprite = pawnSprite;
            sr.sortingOrder = 10;
            Debug.Log($"[GeneratePawnPrefab] pawnSprite={(pawnSprite == null ? "NULL" : pawnSprite.name)} sortingOrder={sr.sortingOrder}");
            // Day 35 fix: if sprite was null, force-color the renderer
            // so the pawn is at least visible.
            if (pawnSprite == null)
            {
                sr.color = new Color(1f, 0.5f, 0.3f, 1f);
                Debug.LogError("[GeneratePawnPrefab] PAWN SPRITE NULL — using flat color fallback");
            }
            BoxCollider2D col = pawnGo.AddComponent<BoxCollider2D>();
            col.size = new Vector2(2f, 2f);
            pawnGo.AddComponent<PawnEntity>();
            pawnGo.AddComponent<PawnMovement>();
            pawnGo.AddComponent<PawnNeeds>();
            pawnGo.AddComponent<PawnChopper>();
            pawnGo.AddComponent<PawnGatherer>();  // Day 11 — berry gather
            pawnGo.AddComponent<PawnHunter>();    // Day 24 — auto-hunt animals
            pawnGo.AddComponent<PawnCook>();      // Day 26 — auto-cook at stove
            pawnGo.AddComponent<PawnSkills>();    // Day 19 — XP/level per skill
            // Day 30 PawnNameLabel temporarily removed — suspected of hiding sprite (Day 34 debug)
            pawnGo.AddComponent<PawnUtilityAI>();

            PrefabUtility.SaveAsPrefabAsset(pawnGo, PawnPrefabPath);
            Object.DestroyImmediate(pawnGo);
            Debug.Log($"[SceneSetup] Pawn prefab -> {PawnPrefabPath}");
        }

        private static void GenerateMainMenu()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // Camera
            GameObject camGo = new GameObject("Main Camera");
            Camera cam = camGo.AddComponent<Camera>();
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.05f, 0.05f, 0.08f, 1f);
            cam.orthographic = true;
            cam.orthographicSize = 5f;
            camGo.tag = "MainCamera";
            camGo.AddComponent<AudioListener>();

            // EventSystem (required for UI input)
            GameObject esGo = new GameObject("EventSystem");
            esGo.AddComponent<UnityEngine.EventSystems.EventSystem>();
            esGo.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();

            // Canvas
            GameObject canvasGo = new GameObject("Canvas");
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGo.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            canvasGo.AddComponent<GraphicRaycaster>();

            // Title text
            GameObject titleGo = new GameObject("Title");
            titleGo.transform.SetParent(canvasGo.transform, false);
            Text title = titleGo.AddComponent<Text>();
            title.text = "PAWN SIM\n(RimWorld-lite vertical slice)";
            title.alignment = TextAnchor.MiddleCenter;
            title.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            title.fontSize = 36;
            title.color = new Color(0.95f, 0.95f, 0.9f, 1f);
            RectTransform titleRt = titleGo.GetComponent<RectTransform>();
            titleRt.anchorMin = new Vector2(0.5f, 0.7f);
            titleRt.anchorMax = new Vector2(0.5f, 0.7f);
            titleRt.sizeDelta = new Vector2(800, 200);
            titleRt.anchoredPosition = Vector2.zero;

            // Start button
            GameObject startGo = CreateMenuButton(canvasGo.transform, "StartButton", "Start Game", new Vector2(0.5f, 0.45f));
            Button startBtn = startGo.GetComponent<Button>();

            // Quit button
            GameObject quitGo = CreateMenuButton(canvasGo.transform, "QuitButton", "Quit", new Vector2(0.5f, 0.30f));
            Button quitBtn = quitGo.GetComponent<Button>();

            // Controller
            GameObject controllerGo = new GameObject("MainMenuController");
            MainMenuController ctrl = controllerGo.AddComponent<MainMenuController>();
            SerializedObject so = new SerializedObject(ctrl);
            so.FindProperty("startButton").objectReferenceValue = startBtn;
            so.FindProperty("quitButton").objectReferenceValue = quitBtn;
            so.FindProperty("gameSceneName").stringValue = "Game";
            so.ApplyModifiedProperties();

            // Persistent button listeners (baked into scene file — fires even
            // if Awake-time runtime wiring fails for any reason)
            UnityAction startAction = new UnityAction(ctrl.OnStartClicked);
            UnityEventTools.AddPersistentListener(startBtn.onClick, startAction);
            UnityAction quitAction = new UnityAction(ctrl.OnQuitClicked);
            UnityEventTools.AddPersistentListener(quitBtn.onClick, quitAction);
            Debug.Log("[SceneSetup] MainMenu — persistent onClick listeners baked");

            EditorSceneManager.SaveScene(scene, MainMenuPath);
            Debug.Log($"[SceneSetup] MainMenu -> {MainMenuPath}");
        }

        private static GameObject CreateMenuButton(Transform parent, string name, string label, Vector2 anchor)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);

            Image img = go.AddComponent<Image>();
            img.color = new Color(0.2f, 0.5f, 0.8f, 1f);

            Button btn = go.AddComponent<Button>();
            ColorBlock colors = btn.colors;
            colors.normalColor = new Color(0.2f, 0.5f, 0.8f, 1f);
            colors.highlightedColor = new Color(0.3f, 0.6f, 0.9f, 1f);
            colors.pressedColor = new Color(0.15f, 0.4f, 0.7f, 1f);
            btn.colors = colors;

            RectTransform rt = go.GetComponent<RectTransform>();
            rt.anchorMin = anchor;
            rt.anchorMax = anchor;
            rt.sizeDelta = new Vector2(280, 70);
            rt.anchoredPosition = Vector2.zero;

            // Label
            GameObject txtGo = new GameObject("Text");
            txtGo.transform.SetParent(go.transform, false);
            Text txt = txtGo.AddComponent<Text>();
            txt.text = label;
            txt.alignment = TextAnchor.MiddleCenter;
            txt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            txt.fontSize = 22;
            txt.color = Color.white;
            RectTransform txtRt = txtGo.GetComponent<RectTransform>();
            txtRt.anchorMin = Vector2.zero;
            txtRt.anchorMax = Vector2.one;
            txtRt.sizeDelta = Vector2.zero;
            txtRt.anchoredPosition = Vector2.zero;

            return go;
        }

        private static void GenerateGame()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // Camera
            GameObject camGo = new GameObject("Main Camera");
            Camera cam = camGo.AddComponent<Camera>();
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.15f, 0.18f, 0.13f, 1f);
            cam.orthographic = true;
            // Day 37: 8 -> 7 살짝 줌인 (pawn 가시성 ↑).  여전히 20x20 grass
            //  대부분이 화면 안에 들어옴 (vertical ±7, horizontal ±12.4 at 16:9).
            cam.orthographicSize = 7f;
            camGo.tag = "MainCamera";
            camGo.transform.position = new Vector3(0, 0, -10);
            camGo.AddComponent<AudioListener>();
            // Day 8: WASD pan + mouse-wheel zoom + Shift fast-pan
            camGo.AddComponent<CameraController>();
            // Day 9: tint camera background by time of day
            camGo.AddComponent<DayNightCycle>();

            // EventSystem
            GameObject esGo = new GameObject("EventSystem");
            esGo.AddComponent<UnityEngine.EventSystems.EventSystem>();
            esGo.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();

            // Day 8: TimeController singleton (1x/2x/4x + Space pause)
            GameObject tcGo = new GameObject("TimeController");
            tcGo.AddComponent<TimeController>();

            // Day 9: GameClock singleton (in-game day/hour/minute)
            GameObject gcGo = new GameObject("GameClock");
            gcGo.AddComponent<GameClock>();

            // Tilemap parent (Grid)
            GameObject gridGo = new GameObject("Grid");
            Grid grid = gridGo.AddComponent<Grid>();
            grid.cellSize = new Vector3(1, 1, 0);

            GameObject tmGo = new GameObject("Ground");
            tmGo.transform.SetParent(gridGo.transform);
            Tilemap tm = tmGo.AddComponent<Tilemap>();
            TilemapRenderer tmr = tmGo.AddComponent<TilemapRenderer>();
            tmr.sortingOrder = 0;

            // Create grass tile asset
            Tile grassTile = ScriptableObject.CreateInstance<Tile>();
            Sprite grassSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/tile_grass.png");
            if (grassSprite == null)
            {
                string assetPath = "Assets/Sprites/tile_grass.png";
                TextureImporter ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 16;
                    ti.SaveAndReimport();
                    grassSprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                }
            }
            grassTile.sprite = grassSprite;
            Directory.CreateDirectory("Assets/Tiles");
            AssetDatabase.CreateAsset(grassTile, "Assets/Tiles/Grass.asset");

            // Fill 20x20 grass
            for (int x = -10; x < 10; x++)
            {
                for (int y = -10; y < 10; y++)
                {
                    tm.SetTile(new Vector3Int(x, y, 0), grassTile);
                }
            }

            // GameManager + spawn pawn via prefab
            GameObject gmGo = new GameObject("GameManager");
            GameManager gm = gmGo.AddComponent<GameManager>();
            GameObject pawnPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(PawnPrefabPath);
            SerializedObject gmSo = new SerializedObject(gm);
            gmSo.FindProperty("pawnPrefab").objectReferenceValue = pawnPrefab;
            gmSo.ApplyModifiedProperties();

            // ResourceManager (singleton)
            GameObject rmGo = new GameObject("ResourceManager");
            rmGo.AddComponent<ResourceManager>();

            // AudioBank (Day 6 - wired Day 7)
            GameObject audioGo = new GameObject("AudioBank");
            AudioBank audioBank = audioGo.AddComponent<AudioBank>();
            AudioClip chopClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/chop.wav");
            AudioClip selClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/select.wav");
            // Day 33: ambient BGM (30s loop)
            if (File.Exists("Assets/Audio/bgm_ambient.wav"))
                AssetDatabase.ImportAsset("Assets/Audio/bgm_ambient.wav", ImportAssetOptions.ForceUpdate);
            AudioClip bgmClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/bgm_ambient.wav");
            SerializedObject abSo = new SerializedObject(audioBank);
            if (chopClip != null) abSo.FindProperty("sfxChop").objectReferenceValue = chopClip;
            if (selClip != null) abSo.FindProperty("sfxSelect").objectReferenceValue = selClip;
            if (bgmClip != null) abSo.FindProperty("bgm").objectReferenceValue = bgmClip;
            abSo.ApplyModifiedProperties();

            // AI Director (Day 5)
            GameObject dirGo = new GameObject("AIDirector");
            AIDirector director = dirGo.AddComponent<AIDirector>();

            // Day 22: WeatherController — subscribes to AIDirector storm event
            GameObject wcGo = new GameObject("WeatherController");
            WeatherController wc = wcGo.AddComponent<WeatherController>();
            wc.SetRefs(director);

            // Day 23: 5 wandering deer (peaceful food source)
            Sprite deerSpr = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/deer.png");
            Vector2[] deerPositions = new[]
            {
                new Vector2(-8f,  3f),
                new Vector2( 8f,  5f),
                new Vector2( 9f, -4f),
                new Vector2(-9f, -5f),
                new Vector2( 0f,  8f),
            };
            foreach (var dpos in deerPositions)
            {
                GameObject dGo = new GameObject($"Deer_{dpos.x}_{dpos.y}");
                dGo.transform.position = new Vector3(dpos.x, dpos.y, 0);
                var dsr2 = dGo.AddComponent<SpriteRenderer>();
                dsr2.sprite = deerSpr;
                dsr2.sortingOrder = 8;
                dGo.AddComponent<Rigidbody2D>();
                var dcol = dGo.AddComponent<CircleCollider2D>();
                dcol.radius = 0.4f;
                dGo.AddComponent<AnimalEntity>();
            }

            // Trees — sprinkle 8 around the map (Day 3)
            Sprite treeSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/tree.png");
            if (treeSprite == null)
            {
                string p = "Assets/Sprites/tree.png";
                TextureImporter ti = AssetImporter.GetAtPath(p) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 16;
                    ti.SaveAndReimport();
                    treeSprite = AssetDatabase.LoadAssetAtPath<Sprite>(p);
                }
            }
            // Day 12: build a Tree prefab asset once, then Instantiate for the
            // initial scatter AND hand the prefab reference to RegrowthScheduler
            // so saplings can promote to a fresh tree.  This unifies the
            // initial-scatter and regen code paths (Option B from the handoff).
            GameObject treeTemplate = new GameObject("Tree");
            SpriteRenderer templateSr = treeTemplate.AddComponent<SpriteRenderer>();
            templateSr.sprite = treeSprite;
            templateSr.sortingOrder = 5;
            BoxCollider2D templateCol = treeTemplate.AddComponent<BoxCollider2D>();
            templateCol.size = new Vector2(1.5f, 1.5f);
            treeTemplate.AddComponent<TreeEntity>();
            GameObject treePrefab = PrefabUtility.SaveAsPrefabAsset(treeTemplate, TreePrefabPath);
            Object.DestroyImmediate(treeTemplate);
            Debug.Log($"[SceneSetup] Tree prefab -> {TreePrefabPath}");

            Vector2[] treePositions = new[]
            {
                new Vector2(-5,  4),
                new Vector2( 6,  3),
                new Vector2(-3, -4),
                new Vector2( 4, -5),
                new Vector2(-7,  0),
                new Vector2( 7,  0),
                new Vector2( 0,  6),
                new Vector2( 0, -7),
            };
            foreach (var pos in treePositions)
            {
                GameObject t = (GameObject)PrefabUtility.InstantiatePrefab(treePrefab);
                t.name = $"Tree_{pos.x}_{pos.y}";
                t.transform.position = new Vector3(pos.x, pos.y, 0);
            }

            // Day 12: RegrowthScheduler — drives bush regen + tree-to-sapling
            // chains.  Created AFTER treePrefab exists so we can wire it.
            // Lesson #7 firewall: callers poll Instance from Update, never
            // subscribe in OnEnable — singleton bind order isn't guaranteed.
            GameObject rsGo = new GameObject("RegrowthScheduler");
            RegrowthScheduler rs = rsGo.AddComponent<RegrowthScheduler>();
            rs.SetTreePrefab(treePrefab);

            // Day 17-18: Build mode — Wall + Floor + Door prefabs + manager.
            Sprite wallSprite  = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/wall_wood.png");
            Sprite floorSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/floor_wood.png");
            Sprite doorSprite  = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/door_wood.png");

            GameObject wallTemplate = new GameObject("Wall");
            var wsr = wallTemplate.AddComponent<SpriteRenderer>();
            wsr.sprite = wallSprite; wsr.sortingOrder = 7;
            var wbox = wallTemplate.AddComponent<BoxCollider2D>(); wbox.size = Vector2.one;
            wallTemplate.AddComponent<WallEntity>();
            GameObject wallPrefab = PrefabUtility.SaveAsPrefabAsset(wallTemplate, "Assets/Prefabs/Wall.prefab");
            Object.DestroyImmediate(wallTemplate);

            GameObject floorTemplate = new GameObject("Floor");
            var fsr = floorTemplate.AddComponent<SpriteRenderer>();
            fsr.sprite = floorSprite; fsr.sortingOrder = 1;
            floorTemplate.AddComponent<FloorEntity>();
            GameObject floorPrefab = PrefabUtility.SaveAsPrefabAsset(floorTemplate, "Assets/Prefabs/Floor.prefab");
            Object.DestroyImmediate(floorTemplate);

            GameObject doorTemplate = new GameObject("Door");
            var dsr = doorTemplate.AddComponent<SpriteRenderer>();
            dsr.sprite = doorSprite; dsr.sortingOrder = 6;
            var dbox = doorTemplate.AddComponent<BoxCollider2D>(); dbox.size = Vector2.one; dbox.isTrigger = true;
            doorTemplate.AddComponent<DoorEntity>();
            GameObject doorPrefab = PrefabUtility.SaveAsPrefabAsset(doorTemplate, "Assets/Prefabs/Door.prefab");
            Object.DestroyImmediate(doorTemplate);

            // Day 25: Stove prefab
            Sprite stoveSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/stove.png");
            GameObject stoveTemplate = new GameObject("Stove");
            var ssr = stoveTemplate.AddComponent<SpriteRenderer>();
            ssr.sprite = stoveSprite; ssr.sortingOrder = 5;
            var sbox = stoveTemplate.AddComponent<BoxCollider2D>(); sbox.size = Vector2.one;
            stoveTemplate.AddComponent<StoveEntity>();
            GameObject stovePrefab = PrefabUtility.SaveAsPrefabAsset(stoveTemplate, "Assets/Prefabs/Stove.prefab");
            Object.DestroyImmediate(stoveTemplate);

            GameObject ghostGo = new GameObject("BuildGhost");
            var ghostSr = ghostGo.AddComponent<SpriteRenderer>();
            ghostSr.sprite = wallSprite;
            ghostSr.sortingOrder = 20;
            ghostSr.color = new Color(1f, 1f, 1f, 0.5f);
            ghostSr.enabled = false;

            GameObject bmGo = new GameObject("BuildManager");
            BuildManager bm = bmGo.AddComponent<BuildManager>();
            bm.SetRefs(wallPrefab, floorPrefab, doorPrefab, stovePrefab,
                       wallSprite, floorSprite, doorSprite, stoveSprite, ghostSr);

            // Day 11: BerryBushes — 4 placed offset from trees so AI sees
            // both gather + chop choices.  Re-use tree sprite tinted greenish
            // until an operator-authored berry sprite exists (already imported
            // by ForceImportAllSprites, so no extra import call needed).
            // NOTE: BerryBushEntity.Awake() repaints SpriteRenderer.color
            // based on stock level (white -> grey), so any green tint we set
            // here is overwritten at runtime — that's intentional in the
            // component design and acceptable: white vs brown still reads
            // distinct from trees.  The scene-file color is still set per
            // handoff spec.
            Vector2[] bushPositions = new[]
            {
                new Vector2(-5f, -2f),
                new Vector2( 2f,  4f),
                new Vector2( 5f, -3f),
                new Vector2(-3f,  5f),
            };
            foreach (var pos in bushPositions)
            {
                GameObject b = new GameObject($"BerryBush_{pos.x}_{pos.y}");
                b.transform.position = new Vector3(pos.x, pos.y, 0);
                SpriteRenderer bsr = b.AddComponent<SpriteRenderer>();
                bsr.sprite = treeSprite;
                bsr.sortingOrder = 5;
                bsr.color = new Color(0.6f, 0.9f, 0.4f, 1f);
                BoxCollider2D bcol = b.AddComponent<BoxCollider2D>();
                bcol.size = Vector2.one;
                b.AddComponent<BerryBushEntity>();
            }

            // ClickSelector
            GameObject csGo = new GameObject("ClickSelector");
            ClickSelector cs = csGo.AddComponent<ClickSelector>();

            // AutoScreenshotter (self-validation harness)
            GameObject ssGo = new GameObject("AutoScreenshotter");
            ssGo.AddComponent<AutoScreenshotter>();

            // ================================================================
            // Day 14 UI polish — palette + layout refactor.
            // Palette (mirror in TimeUI.cs):
            //   panel        = rgba(0.10, 0.094, 0.078, 0.85)
            //   accent_wood  = #a87543  (0.659, 0.459, 0.263)
            //   accent_food  = #7a9a4d  (0.478, 0.604, 0.302)
            //   accent_warn  = #c45a3a  (0.769, 0.353, 0.227)
            //   text_primary = #e8dfd0  (0.910, 0.875, 0.816)
            //   text_muted   = #8a8170  (0.541, 0.506, 0.439)
            // ================================================================
            Color colPanel       = new Color(0.10f, 0.094f, 0.078f, 0.85f);
            Color colAccentWood  = new Color(0.659f, 0.459f, 0.263f, 1f);
            Color colAccentFood  = new Color(0.478f, 0.604f, 0.302f, 1f);
            Color colAccentWarn  = new Color(0.769f, 0.353f, 0.227f, 1f);
            Color colTextPrimary = new Color(0.910f, 0.875f, 0.816f, 1f);
            Color colTextMuted   = new Color(0.541f, 0.506f, 0.439f, 1f);
            // Korean font: try multiple OS fonts.  Malgun Gothic on Win10/11
            // is the safe default.  NanumGothic for Win7 installs that
            // grabbed the Nanum package separately.  Gulim is the legacy
            // shipped Korean font.  Final fallback = LegacyRuntime.ttf
            // (no Hangul → squares, but at least loads).
            Font  uiFont         = Font.CreateDynamicFontFromOSFont(
                new[] { "Malgun Gothic", "NanumGothic", "Gulim", "Dotum", "Arial Unicode MS" }, 22)
                                  ?? Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");

            // Canvas (EventSystem already created earlier)
            GameObject canvasGo = new GameObject("Canvas");
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGo.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            canvasGo.AddComponent<GraphicRaycaster>();

            // ---------- TopBar (full-width strip, 32px, panel color) ----------
            GameObject topBarGo = new GameObject("TopBar");
            topBarGo.transform.SetParent(canvasGo.transform, false);
            Image topBarBg = topBarGo.AddComponent<Image>();
            topBarBg.color = colPanel;
            RectTransform topRt = topBarGo.GetComponent<RectTransform>();
            topRt.anchorMin = new Vector2(0f, 1f);
            topRt.anchorMax = new Vector2(1f, 1f);
            topRt.pivot = new Vector2(0.5f, 1f);
            topRt.sizeDelta = new Vector2(0, 32);
            topRt.anchoredPosition = new Vector2(0, 0);

            // TopBar LEFT — ClockUI "Day 1 - 06:00"
            GameObject clockGo = new GameObject("ClockUI");
            clockGo.transform.SetParent(topBarGo.transform, false);
            Text clockText = clockGo.AddComponent<Text>();
            clockText.text = "Day 1 - 06:00";
            clockText.font = uiFont;
            clockText.fontSize = 22;
            clockText.color = colTextPrimary;
            clockText.alignment = TextAnchor.MiddleLeft;
            RectTransform clockRt = clockGo.GetComponent<RectTransform>();
            clockRt.anchorMin = new Vector2(0f, 0f);
            clockRt.anchorMax = new Vector2(0f, 1f);
            clockRt.pivot = new Vector2(0f, 0.5f);
            clockRt.sizeDelta = new Vector2(220, 0);
            clockRt.anchoredPosition = new Vector2(16, 0);
            clockGo.AddComponent<ClockUI>();

            // TopBar CENTER — TimeUI "▶ 1x"
            GameObject timeGo = new GameObject("TimeUI");
            timeGo.transform.SetParent(topBarGo.transform, false);
            Text timeText = timeGo.AddComponent<Text>();
            timeText.text = "▶ 1x";
            timeText.font = uiFont;
            timeText.fontSize = 22;
            timeText.color = colTextPrimary;
            timeText.alignment = TextAnchor.MiddleCenter;
            RectTransform timeRt = timeGo.GetComponent<RectTransform>();
            timeRt.anchorMin = new Vector2(0.5f, 0f);
            timeRt.anchorMax = new Vector2(0.5f, 1f);
            timeRt.pivot = new Vector2(0.5f, 0.5f);
            timeRt.sizeDelta = new Vector2(220, 0);
            timeRt.anchoredPosition = new Vector2(0, 0);
            timeGo.AddComponent<TimeUI>();

            // TopBar RIGHT — Wood / Food counter (no separate panel — inline in topbar)
            GameObject woodGo = new GameObject("WoodText");
            woodGo.transform.SetParent(topBarGo.transform, false);
            Text woodText = woodGo.AddComponent<Text>();
            woodText.text = "목재: 0";
            woodText.font = uiFont;
            woodText.fontSize = 22;
            woodText.color = colAccentWood;
            woodText.alignment = TextAnchor.MiddleRight;
            RectTransform woodRt = woodGo.GetComponent<RectTransform>();
            woodRt.anchorMin = new Vector2(1f, 0f);
            woodRt.anchorMax = new Vector2(1f, 1f);
            woodRt.pivot = new Vector2(1f, 0.5f);
            woodRt.sizeDelta = new Vector2(140, 0);
            woodRt.anchoredPosition = new Vector2(-320, 0);

            GameObject sepGo = new GameObject("ResSep1");
            sepGo.transform.SetParent(topBarGo.transform, false);
            Text sepText = sepGo.AddComponent<Text>();
            sepText.text = "·";
            sepText.font = uiFont;
            sepText.fontSize = 22;
            sepText.color = colTextMuted;
            sepText.alignment = TextAnchor.MiddleCenter;
            RectTransform sepRt = sepGo.GetComponent<RectTransform>();
            sepRt.anchorMin = new Vector2(1f, 0f);
            sepRt.anchorMax = new Vector2(1f, 1f);
            sepRt.pivot = new Vector2(0.5f, 0.5f);
            sepRt.sizeDelta = new Vector2(12, 0);
            sepRt.anchoredPosition = new Vector2(-310, 0);

            GameObject sep2Go = new GameObject("ResSep2");
            sep2Go.transform.SetParent(topBarGo.transform, false);
            Text sep2Text = sep2Go.AddComponent<Text>();
            sep2Text.text = "·";
            sep2Text.font = uiFont;
            sep2Text.fontSize = 22;
            sep2Text.color = colTextMuted;
            sep2Text.alignment = TextAnchor.MiddleCenter;
            RectTransform sep2Rt = sep2Go.GetComponent<RectTransform>();
            sep2Rt.anchorMin = new Vector2(1f, 0f);
            sep2Rt.anchorMax = new Vector2(1f, 1f);
            sep2Rt.pivot = new Vector2(0.5f, 0.5f);
            sep2Rt.sizeDelta = new Vector2(12, 0);
            sep2Rt.anchoredPosition = new Vector2(-170, 0);

            GameObject foodTextGo = new GameObject("FoodText");
            foodTextGo.transform.SetParent(topBarGo.transform, false);
            // (separator above already created by build-engineer Day 14 pass)

            Text foodText = foodTextGo.AddComponent<Text>();
            foodText.text = "식량: 0";
            foodText.font = uiFont;
            foodText.fontSize = 22;
            foodText.color = colAccentFood;
            foodText.alignment = TextAnchor.MiddleLeft;
            RectTransform foodTextRt = foodTextGo.GetComponent<RectTransform>();
            foodTextRt.anchorMin = new Vector2(1f, 0f);
            foodTextRt.anchorMax = new Vector2(1f, 1f);
            foodTextRt.pivot = new Vector2(1f, 0.5f);
            foodTextRt.sizeDelta = new Vector2(140, 0);
            foodTextRt.anchoredPosition = new Vector2(-20, 0);

            // Day 29: meals counter (식사)
            GameObject mealsTextGo = new GameObject("MealsText");
            mealsTextGo.transform.SetParent(topBarGo.transform, false);
            Text mealsText = mealsTextGo.AddComponent<Text>();
            mealsText.text = "식사: 0";
            mealsText.font = uiFont;
            mealsText.fontSize = 22;
            mealsText.color = new Color(0.93f, 0.81f, 0.45f, 1f);  // amber/wheat
            mealsText.alignment = TextAnchor.MiddleLeft;
            RectTransform mealsRt = mealsTextGo.GetComponent<RectTransform>();
            mealsRt.anchorMin = new Vector2(1f, 0f);
            mealsRt.anchorMax = new Vector2(1f, 1f);
            mealsRt.pivot = new Vector2(1f, 0.5f);
            mealsRt.sizeDelta = new Vector2(140, 0);
            mealsRt.anchoredPosition = new Vector2(-160, 0);

            // ResourceCounterUI host (no longer has its own panel image; just script)
            GameObject resHostGo = new GameObject("ResourceCounter");
            resHostGo.transform.SetParent(canvasGo.transform, false);
            resHostGo.AddComponent<RectTransform>();
            ResourceCounterUI resCounter = resHostGo.AddComponent<ResourceCounterUI>();
            SerializedObject rcSo = new SerializedObject(resCounter);
            rcSo.FindProperty("woodText").objectReferenceValue = woodText;
            rcSo.FindProperty("foodText").objectReferenceValue = foodText;
            rcSo.FindProperty("mealsText").objectReferenceValue = mealsText;
            rcSo.ApplyModifiedProperties();

            // ---------- EventLog (right side, 240x160, below topbar) ----------
            GameObject logPanelGo = new GameObject("EventLogPanel");
            logPanelGo.transform.SetParent(canvasGo.transform, false);
            Image logBg = logPanelGo.AddComponent<Image>();
            logBg.color = colPanel;
            RectTransform logRt = logPanelGo.GetComponent<RectTransform>();
            logRt.anchorMin = new Vector2(1f, 1f);
            logRt.anchorMax = new Vector2(1f, 1f);
            logRt.pivot = new Vector2(1f, 1f);
            logRt.sizeDelta = new Vector2(240, 160);
            logRt.anchoredPosition = new Vector2(-12, -44); // 32 topbar + 12 gap

            GameObject logTextGo = new GameObject("LogText");
            logTextGo.transform.SetParent(logPanelGo.transform, false);
            Text logText = logTextGo.AddComponent<Text>();
            logText.text = "";
            logText.font = uiFont;
            logText.fontSize = 16;
            logText.color = colTextPrimary;
            logText.alignment = TextAnchor.UpperLeft;
            logText.supportRichText = true;
            logText.verticalOverflow = VerticalWrapMode.Truncate;
            logText.horizontalOverflow = HorizontalWrapMode.Wrap;
            RectTransform logTextRt = logTextGo.GetComponent<RectTransform>();
            logTextRt.anchorMin = Vector2.zero;
            logTextRt.anchorMax = Vector2.one;
            logTextRt.sizeDelta = new Vector2(-16, -12);
            logTextRt.anchoredPosition = new Vector2(0, -2);

            EventLogUI logUI = logPanelGo.AddComponent<EventLogUI>();
            SerializedObject logSo = new SerializedObject(logUI);
            logSo.FindProperty("director").objectReferenceValue = director;
            logSo.FindProperty("logText").objectReferenceValue = logText;
            logSo.FindProperty("panelBg").objectReferenceValue = logBg;
            logSo.FindProperty("maxEntries").intValue = 3;
            logSo.ApplyModifiedProperties();
            // Day 15: start hidden until first event
            logBg.enabled = false;

            // ---------- PawnInfoPanel (bottom-left, 240x180) ----------
            GameObject panelGo = new GameObject("PawnInfoPanel");
            panelGo.transform.SetParent(canvasGo.transform, false);
            Image panelBg = panelGo.AddComponent<Image>();
            panelBg.color = colPanel;
            RectTransform panelRt = panelGo.GetComponent<RectTransform>();
            panelRt.anchorMin = new Vector2(0f, 0f);
            panelRt.anchorMax = new Vector2(0f, 0f);
            panelRt.pivot = new Vector2(0f, 0f);
            panelRt.sizeDelta = new Vector2(240, 180);
            panelRt.anchoredPosition = new Vector2(12, 64); // leave room for save/load row below

            // Title text (visible when pawn selected)
            GameObject titleGo = new GameObject("Title");
            titleGo.transform.SetParent(panelGo.transform, false);
            Text title = titleGo.AddComponent<Text>();
            title.text = "Colonist";
            title.alignment = TextAnchor.UpperLeft;
            title.font = uiFont;
            title.fontSize = 18;
            title.color = colTextPrimary;
            RectTransform titleRt = titleGo.GetComponent<RectTransform>();
            titleRt.anchorMin = new Vector2(0f, 1f);
            titleRt.anchorMax = new Vector2(1f, 1f);
            titleRt.pivot = new Vector2(0f, 1f);
            titleRt.sizeDelta = new Vector2(-20, 26);
            titleRt.anchoredPosition = new Vector2(10, -8);

            // 3 need bars — accent palette
            Image foodBar  = CreateNeedBar(panelGo.transform, "식량",  new Vector2(10, 105), colAccentFood, uiFont, colTextPrimary);
            Image sleepBar = CreateNeedBar(panelGo.transform, "수면", new Vector2(10, 65),  new Color(0.4f, 0.6f, 0.9f, 1f), uiFont, colTextPrimary);
            Image moodBar  = CreateNeedBar(panelGo.transform, "기분",  new Vector2(10, 25),  colAccentWood, uiFont, colTextPrimary);

            // Empty-state hint — replaces the panel content when no pawn is selected.
            // PawnInfoPanel toggles emptyText visibility based on selection.
            GameObject emptyGo = new GameObject("EmptyText");
            emptyGo.transform.SetParent(panelGo.transform, false);
            Text empty = emptyGo.AddComponent<Text>();
            empty.text = "콜로니스트를 클릭하세요";
            empty.alignment = TextAnchor.MiddleCenter;
            empty.font = uiFont;
            empty.fontSize = 12;
            empty.color = colTextMuted;
            RectTransform emptyRt = emptyGo.GetComponent<RectTransform>();
            emptyRt.anchorMin = Vector2.zero;
            emptyRt.anchorMax = Vector2.one;
            emptyRt.sizeDelta = Vector2.zero;
            emptyRt.anchoredPosition = Vector2.zero;

            // ---------- SaveLoad buttons (bottom-left corner, 40x40 each) ----------
            GameObject saveBtnPanel = new GameObject("SaveLoadButtons");
            saveBtnPanel.transform.SetParent(canvasGo.transform, false);
            RectTransform sbpRt = saveBtnPanel.AddComponent<RectTransform>();
            sbpRt.anchorMin = new Vector2(0f, 0f);
            sbpRt.anchorMax = new Vector2(0f, 0f);
            sbpRt.pivot = new Vector2(0f, 0f);
            sbpRt.sizeDelta = new Vector2(92, 40);
            sbpRt.anchoredPosition = new Vector2(12, 12);

            GameObject saveBtnGo = CreateIconButton(saveBtnPanel.transform, "SaveBtn", "S", new Vector2(0, 0), colPanel, colTextPrimary, uiFont);
            GameObject loadBtnGo = CreateIconButton(saveBtnPanel.transform, "LoadBtn", "L", new Vector2(48, 0), colPanel, colTextPrimary, uiFont);

            GameSaveButtons gsb = saveBtnPanel.AddComponent<GameSaveButtons>();
            SerializedObject gsbSo = new SerializedObject(gsb);
            gsbSo.FindProperty("saveButton").objectReferenceValue = saveBtnGo.GetComponent<Button>();
            gsbSo.FindProperty("loadButton").objectReferenceValue = loadBtnGo.GetComponent<Button>();
            gsbSo.FindProperty("pawnPrefab").objectReferenceValue =
                AssetDatabase.LoadAssetAtPath<GameObject>(PawnPrefabPath);
            gsbSo.FindProperty("treeSprite").objectReferenceValue =
                AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/tree.png");
            gsbSo.ApplyModifiedProperties();

            // ---------- Control hint (bottom-center, muted) ----------
            GameObject hintGo = new GameObject("ControlHint");
            hintGo.transform.SetParent(canvasGo.transform, false);
            Text hintText = hintGo.AddComponent<Text>();
            hintText.text = "WASD/휠/123/Space · B:벽5 · F:바닥1 · G:문3 · T:화덕10 · 1일=4분(1x)";
            hintText.font = uiFont;
            hintText.fontSize = 14;
            Color hintCol = colTextMuted; hintCol.a = 0.75f;
            hintText.color = hintCol;
            hintText.alignment = TextAnchor.MiddleCenter;
            RectTransform hintRt = hintGo.GetComponent<RectTransform>();
            hintRt.anchorMin = new Vector2(0.5f, 0f);
            hintRt.anchorMax = new Vector2(0.5f, 0f);
            hintRt.pivot = new Vector2(0.5f, 0f);
            hintRt.sizeDelta = new Vector2(640, 20);
            hintRt.anchoredPosition = new Vector2(0, 14);

            // Controller wiring
            PawnInfoPanel panel = panelGo.AddComponent<PawnInfoPanel>();
            SerializedObject pso = new SerializedObject(panel);
            pso.FindProperty("selector").objectReferenceValue = cs;
            pso.FindProperty("titleText").objectReferenceValue = title;
            pso.FindProperty("foodBar").objectReferenceValue = foodBar;
            pso.FindProperty("sleepBar").objectReferenceValue = sleepBar;
            pso.FindProperty("moodBar").objectReferenceValue = moodBar;
            pso.FindProperty("emptyText").objectReferenceValue = empty;
            pso.FindProperty("panelBg").objectReferenceValue = panelBg;
            pso.ApplyModifiedProperties();

            // Day 21: SkillUI panel — to the RIGHT of PawnInfoPanel.
            GameObject skillPanelGo = new GameObject("SkillPanel");
            skillPanelGo.transform.SetParent(canvasGo.transform, false);
            Image skillBg = skillPanelGo.AddComponent<Image>();
            skillBg.color = colPanel;
            RectTransform skRt = skillPanelGo.GetComponent<RectTransform>();
            skRt.anchorMin = new Vector2(0f, 0f);
            skRt.anchorMax = new Vector2(0f, 0f);
            skRt.pivot = new Vector2(0f, 0f);
            skRt.sizeDelta = new Vector2(180, 180);
            skRt.anchoredPosition = new Vector2(260, 60);

            Text MkSkillRow(string label, float yOffset, Color accent)
            {
                GameObject g = new GameObject(label + "Text");
                g.transform.SetParent(skillPanelGo.transform, false);
                Text t = g.AddComponent<Text>();
                t.text = $"{label}: Lv 0";
                t.font = uiFont;
                t.fontSize = 16;
                t.color = colTextPrimary;
                t.alignment = TextAnchor.MiddleLeft;
                RectTransform rt = g.GetComponent<RectTransform>();
                rt.anchorMin = new Vector2(0f, 1f);
                rt.anchorMax = new Vector2(1f, 1f);
                rt.pivot = new Vector2(0f, 1f);
                rt.sizeDelta = new Vector2(-16, 24);
                rt.anchoredPosition = new Vector2(8, -yOffset);
                return t;
            }
            Text gatherT = MkSkillRow("채집", 14, colAccentFood);
            Text chopT   = MkSkillRow("벌목", 42, colAccentWood);
            Text buildT  = MkSkillRow("건축", 70, colTextPrimary);
            Text combatT = MkSkillRow("전투", 98, colAccentWarn);

            SkillUI skUI = skillPanelGo.AddComponent<SkillUI>();
            SerializedObject skSo = new SerializedObject(skUI);
            skSo.FindProperty("selector").objectReferenceValue = cs;
            skSo.FindProperty("gatherText").objectReferenceValue = gatherT;
            skSo.FindProperty("chopText").objectReferenceValue = chopT;
            skSo.FindProperty("buildText").objectReferenceValue = buildT;
            skSo.FindProperty("combatText").objectReferenceValue = combatT;
            skSo.FindProperty("container").objectReferenceValue = skillPanelGo;
            skSo.ApplyModifiedProperties();
            skillPanelGo.SetActive(false);  // start hidden until pawn selected

            // Day 21: import + add stove sprite (no scene-time placement;
            // future Day 22 will allow building Stove via BuildManager).
            // For now, just ensure sprite is imported.
            string stovePath = "Assets/Sprites/stove.png";
            if (File.Exists(stovePath))
            {
                AssetDatabase.ImportAsset(stovePath, ImportAssetOptions.ForceUpdate);
                TextureImporter ti = AssetImporter.GetAtPath(stovePath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spriteImportMode = SpriteImportMode.Single;
                    ti.spritePixelsPerUnit = 16;
                    ti.filterMode = FilterMode.Point;
                    ti.SaveAndReimport();
                }
            }

            EditorSceneManager.SaveScene(scene, GamePath);
            Debug.Log($"[SceneSetup] Game -> {GamePath}");
        }

        private static Image CreateNeedBar(Transform parent, string label, Vector2 pos, Color fillColor, Font font = null, Color? labelColor = null)
        {
            if (font == null) font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            Color lblCol = labelColor ?? Color.white;

            // Row container
            GameObject row = new GameObject(label + "Row");
            row.transform.SetParent(parent, false);
            RectTransform rt = row.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0f, 0f);
            rt.anchorMax = new Vector2(0f, 0f);
            rt.pivot = new Vector2(0f, 0f);
            rt.sizeDelta = new Vector2(220, 28);
            rt.anchoredPosition = pos;

            // Label
            GameObject lblGo = new GameObject("Label");
            lblGo.transform.SetParent(row.transform, false);
            Text lbl = lblGo.AddComponent<Text>();
            lbl.text = label;
            lbl.font = font;
            lbl.fontSize = 14;
            lbl.color = lblCol;
            lbl.alignment = TextAnchor.MiddleLeft;
            RectTransform lblRt = lblGo.GetComponent<RectTransform>();
            lblRt.anchorMin = new Vector2(0f, 0f);
            lblRt.anchorMax = new Vector2(0f, 1f);
            lblRt.pivot = new Vector2(0f, 0.5f);
            lblRt.sizeDelta = new Vector2(50, 0);
            lblRt.anchoredPosition = new Vector2(0, 0);

            // Bar bg
            GameObject bgGo = new GameObject("Bg");
            bgGo.transform.SetParent(row.transform, false);
            Image bg = bgGo.AddComponent<Image>();
            bg.color = new Color(0.05f, 0.05f, 0.05f, 0.7f);
            RectTransform bgRt = bgGo.GetComponent<RectTransform>();
            bgRt.anchorMin = new Vector2(0f, 0f);
            bgRt.anchorMax = new Vector2(1f, 1f);
            bgRt.pivot = new Vector2(0f, 0.5f);
            bgRt.sizeDelta = new Vector2(-55, -6);
            bgRt.anchoredPosition = new Vector2(55, 0);

            // Fill
            GameObject fillGo = new GameObject("Fill");
            fillGo.transform.SetParent(bgGo.transform, false);
            Image fill = fillGo.AddComponent<Image>();
            fill.color = fillColor;
            fill.type = Image.Type.Filled;
            fill.fillMethod = Image.FillMethod.Horizontal;
            fill.fillAmount = 0.8f;
            // Use a built-in white sprite so Image actually fills
            fill.sprite = Resources.GetBuiltinResource<Sprite>("UI/Skin/UISprite.psd");
            RectTransform fillRt = fillGo.GetComponent<RectTransform>();
            fillRt.anchorMin = Vector2.zero;
            fillRt.anchorMax = Vector2.one;
            fillRt.sizeDelta = Vector2.zero;
            fillRt.anchoredPosition = Vector2.zero;

            return fill;
        }

        private static GameObject CreateIconButton(Transform parent, string name, string label, Vector2 pos, Color bgColor, Color textColor, Font font)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            Image img = go.AddComponent<Image>();
            img.color = bgColor;
            Button btn = go.AddComponent<Button>();
            ColorBlock cb = btn.colors;
            cb.normalColor = Color.white;
            cb.highlightedColor = new Color(1.15f, 1.15f, 1.15f, 1f);
            cb.pressedColor = new Color(0.7f, 0.7f, 0.7f, 1f);
            btn.colors = cb;

            RectTransform rt = go.GetComponent<RectTransform>();
            rt.anchorMin = new Vector2(0f, 0f);
            rt.anchorMax = new Vector2(0f, 0f);
            rt.pivot = new Vector2(0f, 0f);
            rt.sizeDelta = new Vector2(40, 40);
            rt.anchoredPosition = pos;

            GameObject txtGo = new GameObject("Text");
            txtGo.transform.SetParent(go.transform, false);
            Text txt = txtGo.AddComponent<Text>();
            txt.text = label;
            txt.font = font;
            txt.fontSize = 18;
            txt.fontStyle = FontStyle.Bold;
            txt.color = textColor;
            txt.alignment = TextAnchor.MiddleCenter;
            RectTransform txtRt = txtGo.GetComponent<RectTransform>();
            txtRt.anchorMin = Vector2.zero;
            txtRt.anchorMax = Vector2.one;
            txtRt.sizeDelta = Vector2.zero;
            txtRt.anchoredPosition = Vector2.zero;
            return go;
        }

        private static void RegisterBuildScenes()
        {
            var menuGuid = AssetDatabase.AssetPathToGUID(MainMenuPath);
            var gameGuid = AssetDatabase.AssetPathToGUID(GamePath);
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(MainMenuPath, true),
                new EditorBuildSettingsScene(GamePath, true),
            };
            Debug.Log($"[SceneSetup] BuildScenes registered: MainMenu={menuGuid} Game={gameGuid}");
        }
    }
}
