using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.Tilemaps;
using MelonS.GameProto;

namespace MelonS.GameProto.EditorTools
{
    /// <summary>
    /// One-shot scene generator — creates MainMenu.unity + Game.unity
    /// programmatically and registers them in EditorBuildSettings.
    ///
    /// Invoked from CLI:
    ///   Unity.exe -batchmode -quit -projectPath ... -executeMethod
    ///   MelonS.GameProto.EditorTools.SceneSetup.GenerateAll
    /// </summary>
    public static class SceneSetup
    {
        private const string ScenesDir = "Assets/Scenes";
        private const string MainMenuPath = "Assets/Scenes/MainMenu.unity";
        private const string GamePath = "Assets/Scenes/Game.unity";
        private const string PawnPrefabPath = "Assets/Prefabs/Pawn.prefab";

        [MenuItem("MelonS/Generate All Scenes")]
        public static void GenerateAll()
        {
            Debug.Log("[SceneSetup] Starting generation...");
            Directory.CreateDirectory(ScenesDir);
            Directory.CreateDirectory("Assets/Prefabs");

            GeneratePawnPrefab();
            GenerateMainMenu();
            GenerateGame();
            RegisterBuildScenes();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[SceneSetup] Done.");
        }

        private static void GeneratePawnPrefab()
        {
            // Load the pawn sprite generated by asset_gen
            Sprite pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                "Assets/Sprites/pawn_colonist.png");
            if (pawnSprite == null)
            {
                // Force re-import as Sprite (TextureImporter default may be Default)
                string assetPath = "Assets/Sprites/pawn_colonist.png";
                TextureImporter ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 64;
                    ti.SaveAndReimport();
                    pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                }
            }

            GameObject pawnGo = new GameObject("Pawn");
            SpriteRenderer sr = pawnGo.AddComponent<SpriteRenderer>();
            sr.sprite = pawnSprite;
            sr.sortingOrder = 10;
            BoxCollider2D col = pawnGo.AddComponent<BoxCollider2D>();
            col.size = new Vector2(2f, 2f);
            pawnGo.AddComponent<PawnEntity>();
            pawnGo.AddComponent<PawnMovement>();
            pawnGo.AddComponent<PawnNeeds>();
            pawnGo.AddComponent<PawnChopper>();

            PrefabUtility.SaveAsPrefabAsset(pawnGo, PawnPrefabPath);
            Object.DestroyImmediate(pawnGo);
            Debug.Log($"[SceneSetup] Pawn prefab -> {PawnPrefabPath}");
        }

        private static void GenerateMainMenu()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // Camera
            GameObject camGo = new GameObject("Main Camera");
            Camera cam = camGo.AddComponent<Camera>();
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.05f, 0.05f, 0.08f, 1f);
            cam.orthographic = true;
            cam.orthographicSize = 5f;
            camGo.tag = "MainCamera";
            camGo.AddComponent<AudioListener>();

            // EventSystem (required for UI input)
            GameObject esGo = new GameObject("EventSystem");
            esGo.AddComponent<UnityEngine.EventSystems.EventSystem>();
            esGo.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();

            // Canvas
            GameObject canvasGo = new GameObject("Canvas");
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGo.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            canvasGo.AddComponent<GraphicRaycaster>();

            // Title text
            GameObject titleGo = new GameObject("Title");
            titleGo.transform.SetParent(canvasGo.transform, false);
            Text title = titleGo.AddComponent<Text>();
            title.text = "PAWN SIM\n(RimWorld-lite vertical slice)";
            title.alignment = TextAnchor.MiddleCenter;
            title.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            title.fontSize = 36;
            title.color = new Color(0.95f, 0.95f, 0.9f, 1f);
            RectTransform titleRt = titleGo.GetComponent<RectTransform>();
            titleRt.anchorMin = new Vector2(0.5f, 0.7f);
            titleRt.anchorMax = new Vector2(0.5f, 0.7f);
            titleRt.sizeDelta = new Vector2(800, 200);
            titleRt.anchoredPosition = Vector2.zero;

            // Start button
            GameObject startGo = CreateMenuButton(canvasGo.transform, "StartButton", "Start Game", new Vector2(0.5f, 0.45f));
            Button startBtn = startGo.GetComponent<Button>();

            // Quit button
            GameObject quitGo = CreateMenuButton(canvasGo.transform, "QuitButton", "Quit", new Vector2(0.5f, 0.30f));
            Button quitBtn = quitGo.GetComponent<Button>();

            // Controller
            GameObject controllerGo = new GameObject("MainMenuController");
            MainMenuController ctrl = controllerGo.AddComponent<MainMenuController>();
            SerializedObject so = new SerializedObject(ctrl);
            so.FindProperty("startButton").objectReferenceValue = startBtn;
            so.FindProperty("quitButton").objectReferenceValue = quitBtn;
            so.FindProperty("gameSceneName").stringValue = "Game";
            so.ApplyModifiedProperties();

            EditorSceneManager.SaveScene(scene, MainMenuPath);
            Debug.Log($"[SceneSetup] MainMenu -> {MainMenuPath}");
        }

        private static GameObject CreateMenuButton(Transform parent, string name, string label, Vector2 anchor)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);

            Image img = go.AddComponent<Image>();
            img.color = new Color(0.2f, 0.5f, 0.8f, 1f);

            Button btn = go.AddComponent<Button>();
            ColorBlock colors = btn.colors;
            colors.normalColor = new Color(0.2f, 0.5f, 0.8f, 1f);
            colors.highlightedColor = new Color(0.3f, 0.6f, 0.9f, 1f);
            colors.pressedColor = new Color(0.15f, 0.4f, 0.7f, 1f);
            btn.colors = colors;

            RectTransform rt = go.GetComponent<RectTransform>();
            rt.anchorMin = anchor;
            rt.anchorMax = anchor;
            rt.sizeDelta = new Vector2(280, 70);
            rt.anchoredPosition = Vector2.zero;

            // Label
            GameObject txtGo = new GameObject("Text");
            txtGo.transform.SetParent(go.transform, false);
            Text txt = txtGo.AddComponent<Text>();
            txt.text = label;
            txt.alignment = TextAnchor.MiddleCenter;
            txt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            txt.fontSize = 22;
            txt.color = Color.white;
            RectTransform txtRt = txtGo.GetComponent<RectTransform>();
            txtRt.anchorMin = Vector2.zero;
            txtRt.anchorMax = Vector2.one;
            txtRt.sizeDelta = Vector2.zero;
            txtRt.anchoredPosition = Vector2.zero;

            return go;
        }

        private static void GenerateGame()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // Camera
            GameObject camGo = new GameObject("Main Camera");
            Camera cam = camGo.AddComponent<Camera>();
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.15f, 0.18f, 0.13f, 1f);
            cam.orthographic = true;
            cam.orthographicSize = 8f;
            camGo.tag = "MainCamera";
            camGo.transform.position = new Vector3(0, 0, -10);
            camGo.AddComponent<AudioListener>();

            // EventSystem
            GameObject esGo = new GameObject("EventSystem");
            esGo.AddComponent<UnityEngine.EventSystems.EventSystem>();
            esGo.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();

            // Tilemap parent (Grid)
            GameObject gridGo = new GameObject("Grid");
            Grid grid = gridGo.AddComponent<Grid>();
            grid.cellSize = new Vector3(1, 1, 0);

            GameObject tmGo = new GameObject("Ground");
            tmGo.transform.SetParent(gridGo.transform);
            Tilemap tm = tmGo.AddComponent<Tilemap>();
            TilemapRenderer tmr = tmGo.AddComponent<TilemapRenderer>();
            tmr.sortingOrder = 0;

            // Create grass tile asset
            Tile grassTile = ScriptableObject.CreateInstance<Tile>();
            Sprite grassSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/tile_grass.png");
            if (grassSprite == null)
            {
                string assetPath = "Assets/Sprites/tile_grass.png";
                TextureImporter ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 128;
                    ti.SaveAndReimport();
                    grassSprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                }
            }
            grassTile.sprite = grassSprite;
            Directory.CreateDirectory("Assets/Tiles");
            AssetDatabase.CreateAsset(grassTile, "Assets/Tiles/Grass.asset");

            // Fill 20x20 grass
            for (int x = -10; x < 10; x++)
            {
                for (int y = -10; y < 10; y++)
                {
                    tm.SetTile(new Vector3Int(x, y, 0), grassTile);
                }
            }

            // GameManager + spawn pawn via prefab
            GameObject gmGo = new GameObject("GameManager");
            GameManager gm = gmGo.AddComponent<GameManager>();
            GameObject pawnPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(PawnPrefabPath);
            SerializedObject gmSo = new SerializedObject(gm);
            gmSo.FindProperty("pawnPrefab").objectReferenceValue = pawnPrefab;
            gmSo.ApplyModifiedProperties();

            // ResourceManager (singleton)
            GameObject rmGo = new GameObject("ResourceManager");
            rmGo.AddComponent<ResourceManager>();

            // Trees — sprinkle 8 around the map (Day 3)
            Sprite treeSprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/tree.png");
            if (treeSprite == null)
            {
                string p = "Assets/Sprites/tree.png";
                TextureImporter ti = AssetImporter.GetAtPath(p) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    ti.spritePixelsPerUnit = 64;
                    ti.SaveAndReimport();
                    treeSprite = AssetDatabase.LoadAssetAtPath<Sprite>(p);
                }
            }
            Vector2[] treePositions = new[]
            {
                new Vector2(-5,  4),
                new Vector2( 6,  3),
                new Vector2(-3, -4),
                new Vector2( 4, -5),
                new Vector2(-7,  0),
                new Vector2( 7,  0),
                new Vector2( 0,  6),
                new Vector2( 0, -7),
            };
            foreach (var pos in treePositions)
            {
                GameObject t = new GameObject($"Tree_{pos.x}_{pos.y}");
                t.transform.position = new Vector3(pos.x, pos.y, 0);
                SpriteRenderer tsr = t.AddComponent<SpriteRenderer>();
                tsr.sprite = treeSprite;
                tsr.sortingOrder = 5;
                BoxCollider2D tcol = t.AddComponent<BoxCollider2D>();
                tcol.size = new Vector2(1.5f, 1.5f);
                t.AddComponent<TreeEntity>();
            }

            // ClickSelector
            GameObject csGo = new GameObject("ClickSelector");
            ClickSelector cs = csGo.AddComponent<ClickSelector>();

            // Canvas + PawnInfoPanel (Day 2) — EventSystem already created earlier
            GameObject canvasGo = new GameObject("Canvas");
            Canvas canvas = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGo.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            canvasGo.AddComponent<GraphicRaycaster>();

            // Panel (bottom-left)
            GameObject panelGo = new GameObject("PawnInfoPanel");
            panelGo.transform.SetParent(canvasGo.transform, false);
            Image panelBg = panelGo.AddComponent<Image>();
            panelBg.color = new Color(0f, 0f, 0f, 0.55f);
            RectTransform panelRt = panelGo.GetComponent<RectTransform>();
            panelRt.anchorMin = new Vector2(0f, 0f);
            panelRt.anchorMax = new Vector2(0f, 0f);
            panelRt.pivot = new Vector2(0f, 0f);
            panelRt.sizeDelta = new Vector2(280, 200);
            panelRt.anchoredPosition = new Vector2(20, 20);

            // Title text
            GameObject titleGo = new GameObject("Title");
            titleGo.transform.SetParent(panelGo.transform, false);
            Text title = titleGo.AddComponent<Text>();
            title.text = "Colonist";
            title.alignment = TextAnchor.UpperLeft;
            title.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            title.fontSize = 20;
            title.color = new Color(0.95f, 0.95f, 0.9f, 1f);
            RectTransform titleRt = titleGo.GetComponent<RectTransform>();
            titleRt.anchorMin = new Vector2(0f, 1f);
            titleRt.anchorMax = new Vector2(1f, 1f);
            titleRt.pivot = new Vector2(0f, 1f);
            titleRt.sizeDelta = new Vector2(-20, 30);
            titleRt.anchoredPosition = new Vector2(10, -10);

            // Empty-state text (when no selection)
            GameObject emptyGo = new GameObject("EmptyText");
            emptyGo.transform.SetParent(panelGo.transform, false);
            Text empty = emptyGo.AddComponent<Text>();
            empty.text = "(click pawn to select)";
            empty.alignment = TextAnchor.MiddleCenter;
            empty.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            empty.fontSize = 14;
            empty.color = new Color(0.7f, 0.7f, 0.7f, 1f);
            RectTransform emptyRt = emptyGo.GetComponent<RectTransform>();
            emptyRt.anchorMin = Vector2.zero;
            emptyRt.anchorMax = Vector2.one;
            emptyRt.sizeDelta = Vector2.zero;
            emptyRt.anchoredPosition = Vector2.zero;

            // 3 need bars
            Image foodBar  = CreateNeedBar(panelGo.transform, "Food",  new Vector2(10, 130), new Color(0.4f, 0.8f, 0.4f));
            Image sleepBar = CreateNeedBar(panelGo.transform, "Sleep", new Vector2(10, 90),  new Color(0.4f, 0.6f, 0.9f));
            Image moodBar  = CreateNeedBar(panelGo.transform, "Mood",  new Vector2(10, 50),  new Color(0.9f, 0.7f, 0.4f));

            // Resource counter UI (top-right)
            GameObject resPanelGo = new GameObject("ResourceCounter");
            resPanelGo.transform.SetParent(canvasGo.transform, false);
            Image resBg = resPanelGo.AddComponent<Image>();
            resBg.color = new Color(0f, 0f, 0f, 0.55f);
            RectTransform resRt = resPanelGo.GetComponent<RectTransform>();
            resRt.anchorMin = new Vector2(1f, 1f);
            resRt.anchorMax = new Vector2(1f, 1f);
            resRt.pivot = new Vector2(1f, 1f);
            resRt.sizeDelta = new Vector2(200, 80);
            resRt.anchoredPosition = new Vector2(-20, -20);

            GameObject woodGo = new GameObject("WoodText");
            woodGo.transform.SetParent(resPanelGo.transform, false);
            Text woodText = woodGo.AddComponent<Text>();
            woodText.text = "Wood: 0";
            woodText.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            woodText.fontSize = 18;
            woodText.color = new Color(0.95f, 0.95f, 0.9f, 1f);
            woodText.alignment = TextAnchor.MiddleLeft;
            RectTransform woodRt = woodGo.GetComponent<RectTransform>();
            woodRt.anchorMin = new Vector2(0f, 0.5f);
            woodRt.anchorMax = new Vector2(1f, 1f);
            woodRt.sizeDelta = new Vector2(-20, 0);
            woodRt.anchoredPosition = new Vector2(10, 0);

            GameObject foodTextGo = new GameObject("FoodText");
            foodTextGo.transform.SetParent(resPanelGo.transform, false);
            Text foodText = foodTextGo.AddComponent<Text>();
            foodText.text = "Food: 0";
            foodText.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            foodText.fontSize = 18;
            foodText.color = new Color(0.95f, 0.95f, 0.9f, 1f);
            foodText.alignment = TextAnchor.MiddleLeft;
            RectTransform foodTextRt = foodTextGo.GetComponent<RectTransform>();
            foodTextRt.anchorMin = new Vector2(0f, 0f);
            foodTextRt.anchorMax = new Vector2(1f, 0.5f);
            foodTextRt.sizeDelta = new Vector2(-20, 0);
            foodTextRt.anchoredPosition = new Vector2(10, 0);

            ResourceCounterUI resCounter = resPanelGo.AddComponent<ResourceCounterUI>();
            SerializedObject rcSo = new SerializedObject(resCounter);
            rcSo.FindProperty("woodText").objectReferenceValue = woodText;
            rcSo.FindProperty("foodText").objectReferenceValue = foodText;
            rcSo.ApplyModifiedProperties();

            // Controller
            PawnInfoPanel panel = panelGo.AddComponent<PawnInfoPanel>();
            SerializedObject pso = new SerializedObject(panel);
            pso.FindProperty("selector").objectReferenceValue = cs;
            pso.FindProperty("titleText").objectReferenceValue = title;
            pso.FindProperty("foodBar").objectReferenceValue = foodBar;
            pso.FindProperty("sleepBar").objectReferenceValue = sleepBar;
            pso.FindProperty("moodBar").objectReferenceValue = moodBar;
            pso.FindProperty("emptyText").objectReferenceValue = empty;
            pso.ApplyModifiedProperties();

            EditorSceneManager.SaveScene(scene, GamePath);
            Debug.Log($"[SceneSetup] Game -> {GamePath}");
        }

        private static Image CreateNeedBar(Transform parent, string label, Vector2 pos, Color fillColor)
        {
            // Row container
            GameObject row = new GameObject(label + "Row");
            row.transform.SetParent(parent, false);
            RectTransform rt = row.AddComponent<RectTransform>();
            rt.anchorMin = new Vector2(0f, 0f);
            rt.anchorMax = new Vector2(0f, 0f);
            rt.pivot = new Vector2(0f, 0f);
            rt.sizeDelta = new Vector2(260, 30);
            rt.anchoredPosition = pos;

            // Label
            GameObject lblGo = new GameObject("Label");
            lblGo.transform.SetParent(row.transform, false);
            Text lbl = lblGo.AddComponent<Text>();
            lbl.text = label;
            lbl.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            lbl.fontSize = 14;
            lbl.color = Color.white;
            RectTransform lblRt = lblGo.GetComponent<RectTransform>();
            lblRt.anchorMin = new Vector2(0f, 0f);
            lblRt.anchorMax = new Vector2(0f, 1f);
            lblRt.pivot = new Vector2(0f, 0.5f);
            lblRt.sizeDelta = new Vector2(60, 0);
            lblRt.anchoredPosition = new Vector2(0, 0);

            // Bar bg
            GameObject bgGo = new GameObject("Bg");
            bgGo.transform.SetParent(row.transform, false);
            Image bg = bgGo.AddComponent<Image>();
            bg.color = new Color(0.1f, 0.1f, 0.1f, 0.7f);
            RectTransform bgRt = bgGo.GetComponent<RectTransform>();
            bgRt.anchorMin = new Vector2(0f, 0f);
            bgRt.anchorMax = new Vector2(1f, 1f);
            bgRt.pivot = new Vector2(0f, 0.5f);
            bgRt.sizeDelta = new Vector2(-65, -5);
            bgRt.anchoredPosition = new Vector2(65, 0);

            // Fill
            GameObject fillGo = new GameObject("Fill");
            fillGo.transform.SetParent(bgGo.transform, false);
            Image fill = fillGo.AddComponent<Image>();
            fill.color = fillColor;
            fill.type = Image.Type.Filled;
            fill.fillMethod = Image.FillMethod.Horizontal;
            fill.fillAmount = 0.8f;
            // Use a built-in white sprite so Image actually fills
            fill.sprite = Resources.GetBuiltinResource<Sprite>("UI/Skin/UISprite.psd");
            RectTransform fillRt = fillGo.GetComponent<RectTransform>();
            fillRt.anchorMin = Vector2.zero;
            fillRt.anchorMax = Vector2.one;
            fillRt.sizeDelta = Vector2.zero;
            fillRt.anchoredPosition = Vector2.zero;

            return fill;
        }

        private static void RegisterBuildScenes()
        {
            var menuGuid = AssetDatabase.AssetPathToGUID(MainMenuPath);
            var gameGuid = AssetDatabase.AssetPathToGUID(GamePath);
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(MainMenuPath, true),
                new EditorBuildSettingsScene(GamePath, true),
            };
            Debug.Log($"[SceneSetup] BuildScenes registered: MainMenu={menuGuid} Game={gameGuid}");
        }
    }
}
