using UnityEngine;
using UnityEditor;
using MelonS.GameProto;

namespace MelonS.GameProto.EditorTools
{
    // R4: SceneSetup partial - Pawn prefab 생성만 담당.
    //  원본 SceneSetup.cs(92-145)에서 이동.
    public static partial class SceneSetup
    {
        private static void GeneratePawnPrefab()
        {
            // Load the pawn sprite generated by asset_gen
            Sprite pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                "Assets/Sprites/pawn_colonist.png");
            if (pawnSprite == null)
            {
                // Force re-import as Sprite (TextureImporter default may be Default)
                string assetPath = "Assets/Sprites/pawn_colonist.png";
                TextureImporter ti = AssetImporter.GetAtPath(assetPath) as TextureImporter;
                if (ti != null)
                {
                    ti.textureType = TextureImporterType.Sprite;
                    // #199 A1 - pawn_colonist.png 는 16x16 px.  PPU 16 → 1x1 world unit
                    //  (= grid cell 1x1, RimWorld colonist 와 동일).  ForceImportAllSprites
                    //  (SceneSetup.cs)도 PPU 16 으로 강제하므로 fallback 도 16 으로 일치시킴.
                    ti.spritePixelsPerUnit = 16;
                    ti.filterMode = FilterMode.Point;
                    ti.SaveAndReimport();
                    pawnSprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                }
            }

            GameObject pawnGo = new GameObject("Pawn");
            // #199 A1: RimWorld 와 같이 pawn 은 정확히 1x1 tile 점유.
            //  pawn_colonist.png 는 16x16 px, PPU 16 (ForceImportAllSprites 강제) → 1x1 world unit.
            //  scale 1.0 유지 (PPU 가 1x1 을 만들어내므로 scale 보정 불필요).
            pawnGo.transform.localScale = new Vector3(1f, 1f, 1f);
            // ROOT SpriteRenderer — KEPT EXACTLY AS-IS as the TINT ANCHOR.
            //  GameManager + PawnEntity call GetComponent<SpriteRenderer>() on the
            //  ROOT for per-pawn variant color / selection-yellow / drafted-cyan,
            //  so this component MUST stay on the root, untouched, with its sprite
            //  + sortingOrder set.  Polish v3 V1 walk-bob: to bob the body WITHOUT
            //  moving the root (root transform feeds PathGrid.WorldToCell / cells /
            //  reservations / eject / bars / shadow — moving it desyncs pathfinding,
            //  the exact bug being fixed), the VISIBLE body is drawn by a child
            //  'PawnSpriteBob' renderer that PawnSpriteBob.cs bobs.  We disable the
            //  root renderer's DRAWING (renderer.enabled = false) to avoid a
            //  double-draw, but the component itself stays so all tint callers still
            //  find it; PawnSpriteBob mirrors the root color onto the child each
            //  frame.  See PawnSpriteBob.cs header for the full tint-contract note.
            SpriteRenderer sr = pawnGo.AddComponent<SpriteRenderer>();
            sr.sprite = pawnSprite;
            sr.sortingOrder = 10;
            sr.enabled = false;   // tint anchor only; child draws the visible body
            Debug.Log($"[GeneratePawnPrefab] pawnSprite={(pawnSprite == null ? "NULL" : pawnSprite.name)} sortingOrder={sr.sortingOrder}");
            // Day 35 fix: if sprite was null, force-color the renderer
            // so the pawn is at least visible.
            if (pawnSprite == null)
            {
                sr.color = new Color(1f, 0.5f, 0.3f, 1f);
                Debug.LogError("[GeneratePawnPrefab] PAWN SPRITE NULL — using flat color fallback");
            }
            BoxCollider2D col = pawnGo.AddComponent<BoxCollider2D>();
            // #199 A1: selection/click box 도 1x1 (이전 2x2 는 2x2 sprite 기준이라 stale).
            col.size = new Vector2(1f, 1f);
            pawnGo.AddComponent<PawnEntity>();
            pawnGo.AddComponent<PawnMovement>();
            pawnGo.AddComponent<PawnNeeds>();
            pawnGo.AddComponent<PawnChopper>();
            pawnGo.AddComponent<PawnGatherer>();  // Day 11 — berry gather
            pawnGo.AddComponent<PawnHunter>();    // Day 24 — auto-hunt animals
            pawnGo.AddComponent<PawnCook>();      // Day 26 — auto-cook at stove
            pawnGo.AddComponent<PawnHauler>();    // #116 — wood pile pickup
            pawnGo.AddComponent<PawnHarvester>(); // #202 — ripe crop harvest (survival loop)
            pawnGo.AddComponent<PawnBuilder>();   // #118 — blueprint 건설
            pawnGo.AddComponent<PawnMiner>();     // #119 — 채광
            pawnGo.AddComponent<PawnAbilities>(); // #120 — 능력치 (이동/작업/전투 multiplier)
            pawnGo.AddComponent<PawnThoughts>();  // #122 — mood thoughts (림 breakdown 패턴)
            pawnGo.AddComponent<PawnEquipment>(); // #123 — 의류/무기 equip (mood/방어/공격)
            pawnGo.AddComponent<PawnDoctor>();    // #125 — 부상 동료 치료
            pawnGo.AddComponent<PawnSchedule>();  // #126 — 24h schedule
            pawnGo.AddComponent<PawnSkills>();    // Day 19 — XP/level per skill
            // Stretch 후속: PawnNameLabel 재활성 (Day 30 의심 해소 — 32x32 sprite 와도 OK)
            pawnGo.AddComponent<PawnNameLabel>();
            pawnGo.AddComponent<PawnHealth>();    // Day 45 — body part 6개 health
            pawnGo.AddComponent<PawnTraits>();    // Day 56 — 성격 traits
            pawnGo.AddComponent<PawnWorkSettings>(); // #114 — work priority per pawn
            pawnGo.AddComponent<PawnUtilityAI>();
            pawnGo.AddComponent<PawnFloatingBars>(); // Day 42 — HP/mood floating bars 머리 위

            // Polish v2 — grounding shadow.  Separate child renderer so the
            //  per-pawn variant color / selection-yellow / drafted-cyan logic
            //  (GameManager + PawnEntity both call GetComponent<SpriteRenderer>()
            //  on the ROOT, never children) leaves the shadow untinted.
            //  shadow_small.png is 16x8 @ PPU16 → 1.0 x 0.5 world units, alpha
            //  baked in, so color stays white.  sortingOrder = body(10) − 1 = 9
            //  → renders under the pawn body, same default sortingLayer.
            Sprite shadowSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                "Assets/Sprites/shadow_small.png");
            GameObject shadowGo = new GameObject("PawnShadow");
            shadowGo.transform.SetParent(pawnGo.transform, false);
            shadowGo.transform.localPosition = new Vector3(0f, -0.30f, 0f);
            shadowGo.transform.localScale = Vector3.one;
            var shadowSr = shadowGo.AddComponent<SpriteRenderer>();
            shadowSr.sprite = shadowSprite;
            shadowSr.color = Color.white;            // alpha baked in sprite
            shadowSr.sortingLayerID = sr.sortingLayerID;
            shadowSr.sortingOrder = sr.sortingOrder - 1;  // = 9, under body
            if (shadowSprite == null)
                Debug.LogWarning("[GeneratePawnPrefab] shadow_small.png NULL — pawn shadow skipped");

            // Polish v3 — V1 walk-bob / idle-breathe.  The VISIBLE body sprite
            //  lives on this CHILD so PawnSpriteBob.cs can bob its LOCAL Y without
            //  ever touching the root transform (root drives pathfinding cells /
            //  reservations / eject; bars / nameplate / shadow anchor to root — all
            //  must NOT bob).  Child sortingOrder matches the body (10) and uses the
            //  same sortingLayer as the (now draw-disabled) root renderer, so it
            //  renders exactly where the old root body did, above the shadow (9).
            GameObject bobGo = new GameObject("PawnSpriteBob");
            bobGo.transform.SetParent(pawnGo.transform, false);
            bobGo.transform.localPosition = Vector3.zero;   // authored base; bob adds Y
            bobGo.transform.localScale = Vector3.one;
            var bobSr = bobGo.AddComponent<SpriteRenderer>();
            bobSr.sprite = pawnSprite;
            bobSr.sortingLayerID = sr.sortingLayerID;
            bobSr.sortingOrder = sr.sortingOrder;   // = 10, same as old root body
            bobSr.color = sr.color;                 // initial tint mirror
            if (pawnSprite == null)
            {
                // Mirror the root null-sprite fallback so the pawn stays visible.
                bobSr.color = new Color(1f, 0.5f, 0.3f, 1f);
            }
            var bob = bobGo.AddComponent<PawnSpriteBob>();
            // Wire the bob component to the child it animates + the child renderer
            //  it tint-mirrors.  Uses SerializedObject so private [SerializeField]
            //  refs persist into the prefab asset.
            var bobSo = new SerializedObject(bob);
            bobSo.FindProperty("spriteChild").objectReferenceValue = bobGo.transform;
            bobSo.FindProperty("childRenderer").objectReferenceValue = bobSr;
            // RED-bug fix (W-M1-02 lane A): the bob component lives on the CHILD,
            //  so its old Awake GetComponent<PawnMovement>() / GetComponent<SpriteRenderer>()
            //  resolved to nothing / the child's own renderer.  Wire EXPLICIT refs
            //  to the ROOT components instead:
            //    movementSource   -> root pawnGo's PawnMovement (drives IsMoving → walk-bob)
            //    rootTintRenderer -> root 'sr' tint-anchor (variant/selection/drafted color)
            //  Same SerializedObject pattern as spriteChild/childRenderer so the
            //  refs persist into the prefab asset.
            bobSo.FindProperty("movementSource").objectReferenceValue =
                pawnGo.GetComponent<PawnMovement>();
            bobSo.FindProperty("rootTintRenderer").objectReferenceValue = sr;
            bobSo.ApplyModifiedPropertiesWithoutUndo();

            PrefabUtility.SaveAsPrefabAsset(pawnGo, PawnPrefabPath);
            Object.DestroyImmediate(pawnGo);
            Debug.Log($"[SceneSetup] Pawn prefab -> {PawnPrefabPath}");
        }
    }
}
