// auto-generated by `agent.py gen-editor-scaffold`, filled with VS-lite content.

using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.UI;
using MelonS.GameProto;

namespace MelonS.GameProto.EditorTools
{
    public static class SceneSetup
    {
        private const string ScenesDir = "Assets/Scenes";
        private const string GamePath = "Assets/Scenes/Game.unity";
        private const string PrefabsDir = "Assets/Prefabs";

        private static readonly string[] SpritePaths = new[]
        {
            "Assets/Sprites/player.png",
            "Assets/Sprites/enemy_small.png",
            "Assets/Sprites/enemy_med.png",
            "Assets/Sprites/projectile.png",
            "Assets/Sprites/xp_gem.png",
        };

        private static readonly string[] AudioPaths = new[]
        {
            "Assets/Audio/shoot.wav",
            "Assets/Audio/hit.wav",
            "Assets/Audio/pickup.wav",
            "Assets/Audio/levelup.wav",
        };

        [MenuItem("VSLite/Generate All")]
        public static void GenerateAll()
        {
            Debug.Log("[SceneSetup] Starting...");
            Directory.CreateDirectory(ScenesDir);
            Directory.CreateDirectory(PrefabsDir);

            ForceImportAllAssets();
            var (proj, gem, enemySmall, enemyMed) = BuildPrefabs();
            GenerateGame(proj, gem, enemySmall, enemyMed);
            RegisterBuildScenes();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[SceneSetup] Done.");
        }

        private static void ForceImportAllAssets()
        {
            foreach (var p in SpritePaths)
            {
                if (!File.Exists(p)) { Debug.LogWarning($"[SceneSetup] missing sprite: {p}"); continue; }
                AssetDatabase.ImportAsset(p, ImportAssetOptions.ForceUpdate);
                TextureImporter ti = AssetImporter.GetAtPath(p) as TextureImporter;
                if (ti == null) continue;
                ti.textureType = TextureImporterType.Sprite;
                ti.spriteImportMode = SpriteImportMode.Single;
                ti.spritePixelsPerUnit = 16;
                ti.filterMode = FilterMode.Point;
                ti.SaveAndReimport();
            }
            foreach (var p in AudioPaths)
            {
                if (File.Exists(p))
                    AssetDatabase.ImportAsset(p, ImportAssetOptions.ForceUpdate);
            }
            AssetDatabase.Refresh();
            AssetDatabase.SaveAssets();
        }

        private static (GameObject projectile, GameObject gem, GameObject enemySmall, GameObject enemyMed) BuildPrefabs()
        {
            // Projectile prefab
            var projGo = new GameObject("Projectile");
            var psr = projGo.AddComponent<SpriteRenderer>();
            psr.sprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/projectile.png");
            psr.sortingOrder = 8;
            var pcol = projGo.AddComponent<CircleCollider2D>();
            pcol.isTrigger = true;
            pcol.radius = 0.2f;
            projGo.AddComponent<Projectile>();
            var projPath = $"{PrefabsDir}/Projectile.prefab";
            var projPrefab = PrefabUtility.SaveAsPrefabAsset(projGo, projPath);
            Object.DestroyImmediate(projGo);

            // XP gem prefab
            var gemGo = new GameObject("XPGem");
            var gsr = gemGo.AddComponent<SpriteRenderer>();
            gsr.sprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/xp_gem.png");
            gsr.sortingOrder = 6;
            gemGo.AddComponent<XPGem>();
            var gemPath = $"{PrefabsDir}/XPGem.prefab";
            var gemPrefab = PrefabUtility.SaveAsPrefabAsset(gemGo, gemPath);
            Object.DestroyImmediate(gemGo);

            // Enemy small prefab
            var esGo = new GameObject("EnemySmall");
            var essr = esGo.AddComponent<SpriteRenderer>();
            essr.sprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/enemy_small.png");
            essr.sortingOrder = 5;
            var esrb = esGo.AddComponent<Rigidbody2D>();
            esrb.gravityScale = 0;
            esrb.freezeRotation = true;
            var escol = esGo.AddComponent<CircleCollider2D>();
            escol.radius = 0.4f;
            esGo.AddComponent<EnemyAI>();
            var esEnt = esGo.AddComponent<EnemyEntity>();
            esEnt.SetMaxHp(3);
            esEnt.SetXpPrefab(gemPrefab);
            var enemySmallPath = $"{PrefabsDir}/EnemySmall.prefab";
            var enemySmallPrefab = PrefabUtility.SaveAsPrefabAsset(esGo, enemySmallPath);
            Object.DestroyImmediate(esGo);

            // Enemy med prefab
            var emGo = new GameObject("EnemyMed");
            var emsr = emGo.AddComponent<SpriteRenderer>();
            emsr.sprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/enemy_med.png");
            emsr.sortingOrder = 5;
            var emrb = emGo.AddComponent<Rigidbody2D>();
            emrb.gravityScale = 0;
            emrb.freezeRotation = true;
            var emcol = emGo.AddComponent<CircleCollider2D>();
            emcol.radius = 0.6f;
            var emai = emGo.AddComponent<EnemyAI>();
            var emEnt = emGo.AddComponent<EnemyEntity>();
            emEnt.SetMaxHp(8);
            emEnt.SetXpPrefab(gemPrefab);
            var enemyMedPath = $"{PrefabsDir}/EnemyMed.prefab";
            var enemyMedPrefab = PrefabUtility.SaveAsPrefabAsset(emGo, enemyMedPath);
            Object.DestroyImmediate(emGo);

            return (projPrefab, gemPrefab, enemySmallPrefab, enemyMedPrefab);
        }

        private static void GenerateGame(GameObject projPrefab, GameObject gemPrefab, GameObject enemySmall, GameObject enemyMed)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // Camera
            var camGO = new GameObject("Main Camera");
            var cam = camGO.AddComponent<Camera>();
            cam.orthographic = true;
            cam.orthographicSize = 6f;
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.10f, 0.10f, 0.16f);
            cam.transform.position = new Vector3(0, 0, -10);
            camGO.tag = "MainCamera";
            camGO.AddComponent<AudioListener>();

            // EventSystem
            var esGO = new GameObject("EventSystem");
            esGO.AddComponent<UnityEngine.EventSystems.EventSystem>();
            esGO.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();

            // Player
            var playerGO = new GameObject("Player");
            playerGO.transform.position = Vector3.zero;
            var psr = playerGO.AddComponent<SpriteRenderer>();
            psr.sprite = AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Sprites/player.png");
            psr.sortingOrder = 10;
            var prb = playerGO.AddComponent<Rigidbody2D>();
            prb.gravityScale = 0;
            prb.freezeRotation = true;
            var pcol = playerGO.AddComponent<CircleCollider2D>();
            pcol.radius = 0.5f;
            playerGO.AddComponent<PlayerMovement>();
            playerGO.AddComponent<PlayerHealth>();
            var shooter = playerGO.AddComponent<AutoShooter>();
            shooter.SetProjectilePrefab(projPrefab);

            // Camera follower (simple: in script via Update)
            camGO.AddComponent<CameraFollowPlayer>();

            // XPManager
            var xpGO = new GameObject("XPManager");
            xpGO.AddComponent<XPManager>();

            // AudioBank with clips wired
            var audGO = new GameObject("AudioBank");
            audGO.AddComponent<AudioSource>();
            var ab = audGO.AddComponent<AudioBank>();
            ab.SetClips(
                AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/shoot.wav"),
                AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/hit.wav"),
                AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/pickup.wav"),
                AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Audio/levelup.wav")
            );

            // WaveSpawner
            var spGO = new GameObject("WaveSpawner");
            var ws = spGO.AddComponent<WaveSpawner>();
            ws.SetEnemyPrefabs(new GameObject[] { enemySmall, enemyMed });

            // AutoScreenshotter for qa.py
            var autoGO = new GameObject("AutoScreenshotter");
            autoGO.AddComponent<AutoScreenshotter>();

            // Canvas
            var canvasGO = new GameObject("Canvas");
            var canvas = canvasGO.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGO.AddComponent<CanvasScaler>();
            canvasGO.AddComponent<GraphicRaycaster>();

            // HP text (top-left)
            var hpGO = new GameObject("HPText");
            hpGO.transform.SetParent(canvasGO.transform, false);
            var hpTxt = hpGO.AddComponent<Text>();
            hpTxt.text = "HP: 100";
            hpTxt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            hpTxt.fontSize = 36;
            hpTxt.color = new Color(1f, 0.5f, 0.5f);
            hpTxt.alignment = TextAnchor.UpperLeft;
            var hpRt = hpGO.GetComponent<RectTransform>();
            hpRt.anchorMin = new Vector2(0f, 1f);
            hpRt.anchorMax = new Vector2(0f, 1f);
            hpRt.pivot = new Vector2(0f, 1f);
            hpRt.anchoredPosition = new Vector2(20, -20);
            hpRt.sizeDelta = new Vector2(300, 50);
            var hpHud = hpGO.AddComponent<HUD>();
            hpHud.mode = HUD.Mode.HP;

            // XP text (top-right)
            var xpTextGO = new GameObject("XPText");
            xpTextGO.transform.SetParent(canvasGO.transform, false);
            var xpTxt = xpTextGO.AddComponent<Text>();
            xpTxt.text = "XP: 0";
            xpTxt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            xpTxt.fontSize = 36;
            xpTxt.color = new Color(0.4f, 1f, 0.9f);
            xpTxt.alignment = TextAnchor.UpperRight;
            var xpRt = xpTextGO.GetComponent<RectTransform>();
            xpRt.anchorMin = new Vector2(1f, 1f);
            xpRt.anchorMax = new Vector2(1f, 1f);
            xpRt.pivot = new Vector2(1f, 1f);
            xpRt.anchoredPosition = new Vector2(-20, -20);
            xpRt.sizeDelta = new Vector2(300, 50);
            var xpHud = xpTextGO.AddComponent<HUD>();
            xpHud.mode = HUD.Mode.XP;

            // Hint text (bottom)
            var hintGO = new GameObject("HintText");
            hintGO.transform.SetParent(canvasGO.transform, false);
            var hintTxt = hintGO.AddComponent<Text>();
            hintTxt.text = "WASD to move - auto-shoots nearest enemy - collect cyan gems for XP";
            hintTxt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            hintTxt.fontSize = 18;
            hintTxt.color = new Color(1f, 1f, 1f, 0.5f);
            hintTxt.alignment = TextAnchor.LowerCenter;
            var hintRt = hintGO.GetComponent<RectTransform>();
            hintRt.anchorMin = new Vector2(0f, 0f);
            hintRt.anchorMax = new Vector2(1f, 0f);
            hintRt.pivot = new Vector2(0.5f, 0f);
            hintRt.anchoredPosition = new Vector2(0, 20);
            hintRt.sizeDelta = new Vector2(-40, 30);

            EditorSceneManager.SaveScene(scene, GamePath);
            Debug.Log($"[SceneSetup] saved {GamePath}");
        }

        private static void RegisterBuildScenes()
        {
            var build = new System.Collections.Generic.List<EditorBuildSettingsScene>
            {
                new EditorBuildSettingsScene(GamePath, true),
            };
            EditorBuildSettings.scenes = build.ToArray();
            Debug.Log("[SceneSetup] build scenes registered.");
        }
    }
}
