#!/usr/bin/env bash
# music-video-upload-meta.sh — generate upload-ready metadata
# template for a music-video render.  Output: a markdown file with
# title / description / hashtag suggestions per platform that the
# operator can copy-paste at upload time.
#
# Distinct from scripts/gen-upload-metadata.sh (which handles
# faceless-short narration missions).  Music-videos have no
# narration script + the metadata shape is different (genre +
# music credits instead of topic + B-roll credits).
#
# Usage:
#   scripts/music-video-upload-meta.sh <mission_dir> [--genre=NAME]
#
# Output:
#   <mission_dir>/outputs/upload-metadata.md

set -uo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
# shellcheck disable=SC1091
source "$REPO_ROOT/agents/lib/env.sh" 2>/dev/null || true

MDIR="${1:-}"
GENRE=""
for arg in "$@"; do
  case "$arg" in
    --genre=*) GENRE="${arg#*=}" ;;
  esac
done

if [[ -z "$MDIR" || ! -d "$MDIR" ]]; then
  echo "usage: $0 <mission_dir> [--genre=NAME]" >&2
  exit 64
fi

OUT_DIR="$MDIR/outputs"
[[ -d "$OUT_DIR" ]] || { echo "outputs/ not found in $MDIR" >&2; exit 64; }

# Detect short_id from mission dir name: music-video-<short_id>-<HHMMSS>
MISSION_NAME=$(basename "$MDIR")
SHORT_ID=$(echo "$MISSION_NAME" | sed -E 's/^music-video-(.+)-[0-9]{6}$/\1/')

# Genre fallback: try to infer from short_id, else 'unknown'
if [[ -z "$GENRE" ]]; then
  case "$SHORT_ID" in
    *kpop-ballad*|*kpop_ballad*) GENRE="kpop_ballad" ;;
    *kpop-dance*|*kpop_dance*)   GENRE="kpop_dance" ;;
    *citypop*)                   GENRE="citypop" ;;
    *uspop*)                     GENRE="uspop" ;;
    *rnb*)                       GENRE="rnb" ;;
    *synthwave*)                 GENRE="synthwave" ;;
    *lofi*|*lo-fi*)              GENRE="lofi_hiphop" ;;
    *jazz*)                      GENRE="jazz" ;;
    *)                           GENRE="unknown" ;;
  esac
fi

# Genre-specific hashtag bundles.
case "$GENRE" in
  kpop_ballad) HASH_BASE="#shorts #kpop #kpopballad #한국발라드 #발라드 #emotional #vocal #balladmusic" ;;
  kpop_dance)  HASH_BASE="#shorts #kpop #kpopdance #kpopedm #댄스 #stagelights #kpopstar" ;;
  citypop)     HASH_BASE="#shorts #citypop #시티팝 #80s #neon #aesthetic #vintage #lofi" ;;
  uspop)       HASH_BASE="#shorts #pop #billboard #usapop #vocal #synthpop #cinematic" ;;
  rnb)         HASH_BASE="#shorts #rnb #randb #neosoul #vocal #slowjam #mood" ;;
  synthwave)   HASH_BASE="#shorts #synthwave #retrowave #80s #neon #aesthetic #cyberpunk" ;;
  lofi_hiphop) HASH_BASE="#shorts #lofi #lofihiphop #studymusic #chillvibes #로파이 #공부음악" ;;
  jazz)        HASH_BASE="#shorts #jazz #lofijazz #vinyl #vintage #nightjazz #moodmusic" ;;
  *)           HASH_BASE="#shorts #music #aesthetic" ;;
esac

# Lyric language detection from optional lyric file mentioned in the
# mission's command-line history (best-effort).  Defaults to "unknown".
LYRIC_LANG="unknown"
if ls "$MDIR/resources/clips/raw-korean_"*.mp4 >/dev/null 2>&1 || \
   ls "$MDIR/resources/clips/raw-seoul_"*.mp4 >/dev/null 2>&1; then
  LYRIC_LANG="ko"
fi

# Resolve the rendered mp4 (prefer the final *-lyrics.mp4 if present).
FINAL=""
for cand in "$OUT_DIR"/short-*lyrics.mp4 "$OUT_DIR"/short-*.mp4 "$OUT_DIR/short.mp4"; do
  [[ -f "$cand" ]] && { FINAL="$cand"; break; }
done
if [[ -z "$FINAL" ]]; then
  echo "no rendered mp4 found in $OUT_DIR" >&2
  exit 64
fi

DUR=$("${FFPROBE_BIN:-/opt/homebrew/bin/ffprobe}" -v error \
  -show_entries format=duration -of csv=p=0 "$FINAL" 2>/dev/null | awk '{printf "%d", $1+0.5}')
SIZE=$(du -h "$FINAL" 2>/dev/null | awk '{print $1}')

OUT_META="$OUT_DIR/upload-metadata.md"
cat > "$OUT_META" <<EOF
# Upload metadata — \`$MISSION_NAME\`

> Auto-generated by \`scripts/music-video-upload-meta.sh\`.  Review
> and edit before pasting at upload time.  All copy here is
> templated; nothing is operator-authored yet.

## Render

| Field | Value |
|-------|-------|
| File | \`$FINAL\` |
| Duration | ${DUR}s |
| Size | $SIZE |
| Genre | $GENRE |
| Lyric language | $LYRIC_LANG |
| Short ID | $SHORT_ID |

## YouTube Shorts

**Title** (≤ 70 chars; keep the title TYPED in the operator's voice — do not over-clickbait):
\`\`\`
$(printf '%s\n' "TODO: short evocative title (genre cue + mood phrase, no all-caps)")
\`\`\`

**Description** (≤ 5000 chars; first 2 lines visible on mobile):
\`\`\`
TODO: 1-2 sentence mood description.

🎵 Music: original (Suno)
🎬 B-roll: pexels.com
\`\`\`

**Tags / Hashtags**:
\`\`\`
$HASH_BASE
\`\`\`

## TikTok

**Caption** (≤ 150 chars including hashtags):
\`\`\`
TODO: ≤ 80-char hook
$HASH_BASE
\`\`\`

## Instagram Reels

**Caption** (≤ 2200 chars; first 125 visible in feed):
\`\`\`
TODO: hook line.

$HASH_BASE
\`\`\`

## Attribution (license-required)

- **Music**: Suno (operator-generated, free tier — personal use).
  Verify channel meets monetization-floor exemption before publish.
- **B-roll**: Pexels Free License (attribution appreciated but not
  required).  Per-clip photographer credits are NOT auto-embedded
  in description (operator policy: license doesn't require it).

## Operator next steps

1. Review the TODO sections; replace with operator copy.
2. Upload mp4 + thumbnail (\`${FINAL%.mp4}-thumb.jpg\` if generated).
3. Set scheduled publish time per the channel's cadence.
4. After publish, add the video ID to the channel registry so
   future renders skip its B-roll via the dedup gate.
EOF

echo "[upload-meta] wrote $OUT_META"
echo "[upload-meta]   genre=$GENRE  lang=$LYRIC_LANG  mp4=${DUR}s/$SIZE"
